### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by oknoorap** [replit/kaboom#1]
Congrats. I'm fall in love with your engine. Your engine is easy to read. But I think you should move it to typescript. Just compile it with esbuild with `iife` format, it's fast and modern enough rather than use webpack. 

👍🏻  good job.

**Comment by slmjkdbtl** [comment]
Hi! For sure, typescript + esbuild is actually already in the works, will transform soon.

**Comment by oknoorap** [comment]
thanks, can't wait 😍 !

**Comment by ghlai9665** [comment]
> Hi! For sure, typescript + esbuild is actually already in the works, will transform soon.

Any estimated timeline?

**Comment by slmjkdbtl** [comment]
quite a big change, i'm planning to make it happen after a `v0.2.0` release which will happen in this week

**Comment by oknoorap** [comment]
hey @slmjkdbtl any update? I really want to use this engine 😃 or at least create PR first, maybe I am or someone will contributes, and maybe there is new idea coming up...

**Comment by slmjkdbtl** [comment]
To be honest, after some thought actually I want it to stay a single js file for a while, I think there's certain beauty of no build step, directly runnable, and single file distribution / source code, people can download the file and "own" it, play around with it, somehow I feel a connection between some beautiful single-file libs (e.g. some single header C libs), and that's very hard to happen for big libraries with "modern software development workflows". 

Sorry for the false promise above and enforcing my personal programming beliefs. What I will definitely do now is document the source better and make it more readable, navigable and understandable.

**Comment by bradtaniguchi** [comment]
The "middle-ground" is giving blessing for TS support thru a separate `@types` package, which will move the work of maintaining the types elsewhere. 

Having a simple library+good documentation can provide a good starting point for such a transition for whoever wants to take it up in the future without clogging up this codebase. :)

I personally would like to play around with this library, however I'd end up building the types up myself from the source+docs, or at least looking into grabbing types for it **somehow**, even if that means its a 3rd party type definition.

**Comment by slmjkdbtl** [comment]
That sounds like a good middle ground solution! I'm down for it.

Is the preferred way to add defs to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) project?

**Comment by oknoorap** [comment]
hi @slmjkdbtl, you can build kaboom in single file using esbuild (build typescript as single file), and I think typescript will make your source code more cleaner to read (in github), and people who's want to contributes will understand under the hood what your codes do.

you can also publish kaboom to `npm`, still people can also download it as single files using` unpkg`,
it's a win win solution I think. Please reconsider it 🙇🏻‍♂️

**Comment by slmjkdbtl** [comment]
Ok I will reconsider. Another thing is I'm planning to use embedded JS engines like QuickJS in the future for going native on other platforms, if use typescript will need to make sure the compiler produces valid code that other JS engine won't complain (might not be a big problem)

**Comment by oknoorap** [comment]
I think no need to worry about compiled codes being invalid, because they're both TypeScript or QuickJS are using the same ES20xx specs. 

There is an alternative to QuickJS, it's Deno, they support typescript natively without build tools like NodeJS. In Deno, You can also compile kaboom as a single executable file, so you can make kaboom behave like how Love2D works.

**Comment by slmjkdbtl** [comment]
My only worry is Deno is too heavy for this (also >20mb binaries, we barely need any of its runtime stuff), also lack of proper C ffi (need confirmation) to get into platform native stuff, but will consider

**Comment by oknoorap** [comment]
Deno v1.7 now supports the `--lite` option https://deno.com/blog/v1.7#improvements-to-codedeno-compilecode, and it's reduced size to 40% - 60% smaller than v1.6.

I don't know about c ffi in deno, I'm sure that Rust has a ffi feature, but it seems they haven't implemented it yet to deno. But they support Rust ffi https://github.com/denoland/deno/tree/main/test_plugin

It's not a problem with your plan using QuickJS as long as kaboom use TypeScript 👍🏻

**Comment by slmjkdbtl** [comment]
Closing this as the library has transformed to typescript

**Comment by oknoorap** [comment]
Yay sounds good, thanks @slmjkdbtl

**Comment by slmjkdbtl** [comment]
Np! Typing is fun (not complete yet tho)
