### ISSUE TITLE
kaboom.debug.hoverInfo doesn't seem to respect camera position

### ISSUE THREAD

**Issue by nathanielhudson** [replit/kaboom#10]
Can be seen in https://kaboomjs.com/examples#level

**Expected behavior:**
I should see info on an object after hovering over it regardless of how the camera is positioned.

**Observed behavior:**
![image](https://user-images.githubusercontent.com/2744848/114591616-164afb80-9c58-11eb-8907-8bdb5890a321.png)
![image](https://user-images.githubusercontent.com/2744848/114591696-28c53500-9c58-11eb-9cb7-6a73e25b1171.png)

See cursor position in the above images. Hover calculations appear to be happening irrespective of the current camera transform. As such, you have to position your mouse in unintuitive positions to hover objects.

(By the way - Thank you for the excellent library!)

**Comment by slmjkdbtl** [comment]
Hi! This is actually just fixed in https://github.com/replit/kaboom/commit/e1144d0345f529f7e9c2cc1f26e54bbb7830731b haha! If you refresh the page it should work properly. It's on master now and will be there in the next release

**Comment by nathanielhudson** [comment]
oh lmao

Thank you!
