### ISSUE TITLE
text color and other stylings?

### ISSUE THREAD

**Issue by blurymind** [replit/kaboom#100]
What is the recommended way of styling npc text in kaboomjs? I am asking because Iam thinking of creating a bondagejs plugin.

The idea is to be able to use yarn editor to create npc dialogue and use it in kaboomjs games
https://github.com/YarnSpinnerTool/YarnEditor

online editor demo
https://yarnspinnertool.github.io/YarnEditor/

Yarn can do both bbcode and xml style syntax for styling chunks of text

so I need two elements:
- scrolling text
- multistyle text via tags (bbcode or xml)

Kaboom appears to be able to load fonts, but I couldnt find anything about styling them - color, boldness, etc.

Should a multistyle text be created via many different text objects?
Should such thing be done outside of kaboom?

**Comment by slmjkdbtl** [comment]
You can use `color()` component with `text()` component to create colored text. Kaboom uses bitmap font so it's harder to have built-in bold / italic support, the only way right now is if you provide the bitmap for those styles and change the font property. 

There's no easy way to have multiple styles in a piece of text yet, it'll be very tough to use multiple text objects that can't get formatted as a whole. Some kind of chunked text even formatting syntax support, and it should be done inside kaboom. 

And yeah I'm interested in doing yarn integration. I'll look into bondagejs and yarn's format to see if it can inspired some features here.

**Comment by blurymind** [comment]
I guess for bondagejs, it is not an absolute requirement to have text styling - since that is an extra feature.

As I see it these are separate features that compliment each other very well
- parsing yarn files via bondagejs
-  scrolling text
- text multistyling

So there is a case to be made that each is non blocking and can be added independently as plugins or to the core

The yarn editor has a wrapper for bondagejs already that can be used for inspiration, but a better and more battle tested one is the one that gdevelop is using
https://github.com/4ian/GDevelop/blob/master/Extensions/DialogueTree/dialoguetools.ts

**Comment by slmjkdbtl** [comment]
Related: #431

**Comment by i42lorua** [comment]
And how can you load a font in kaboom? Because I'm trying to load eldelfontmed but I don't know how to do it. I have the .tts of this font but I don't know how to use it in kaboom. And how can I make kaboom to show the ñ or letters with "á"?
