### ISSUE TITLE
Debug Inspector prints position repeatedly when calling object.use(pos()) multiple times

### ISSUE THREAD

**Issue by rarescolibaba** [replit/kaboom#102]
In my code, I call `cursor.use(pos(mousePos()))`, meaning a box gets moved wherever the mouse is. The `cursor.use()` function is called once every click, to save resources (as opposed to calling it every frame).

When I open the inspector, the `pos:` attribute is appended to the data displayed every click (with every call of the `cursor.use()` function):
![inspectorBug](https://user-images.githubusercontent.com/72991062/125506374-264d0b91-6dc6-4995-80b4-e7850322a2d1.gif)

You can more or less see that the `pos` attribute gets repeatedly added each time the position is changed, even though only one set of values is shown across all appearances. This data doesn't disappear when reopening the debug inspector, as refreshing the page is needed.

This may cause FPS drops with many updates (for example, when running `cursor.use()` every frame) when the debug inspector is opened.

**Comment by slmjkdbtl** [comment]
I'll look into it, `use()` should replace the existing comp state.

**Comment by slmjkdbtl** [comment]
It's fixed in v0.6 which will release soon. Also it might be a bit faster to assign `obj.pos = vec2(x, y)`, `use()` does have a bit performance cost
