### ISSUE TITLE
attaching shader as a plugin 

### ISSUE THREAD

**Issue by blurymind** [replit/kaboom#103]
I made a paletteSwap shader as a plugin, however I do not like how I need to add the shader in two lines like so
```
	add([
		sprite("testShades"),
		paletteSwap(palette), // <-- already called it
		shader("paletteSwap") // <--- can this be done inside paletteSwap instead?
	]);
```

full code here:
https://replit.com/@blurymind/paletteSwapShader?v=1

so my question is, if one wants to do shader("paletteSwap")  inside the plugin itself - what life cycle is to be used? Can that be nicely packaged in a plugin and added to any sprite or spritesheet via a single call?

Btw, if you would like me help make this better and there is interest, I can do a pr to add it to kaboom itself? I would love to have a gameboy style palette swap that is as easy as possible to use!

**Comment by slmjkdbtl** [comment]
I think you can do something like 
```js
// a component
function paletteSwap() {
    return {
        // a live cycle method gets called on add()
        add() {
            this.use(shader("paletteSwap"));
        },
        // other stuff
    }
}
```
