### ISSUE TITLE
some concern about the License

### ISSUE THREAD

**Issue by blurymind** [replit/kaboom#104]
I have some concerns about the license being gpl3+ latest
https://github.com/replit/kaboom/blob/master/LICENSE
```
Copyright (C) 2021 Replit

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
```

Correct me if this is wrong, but isnt that license a viral one? Meaning that if I want to release a game, I need to always also release its source code. This is somewhat bad for game engines, since it forces the developer out of using an engine for any sort of commercial work.
If I want to publish and sell something on steam, I need to also release its entire source code too.

This is why godot, gdevelop and most other open source game engines use the MIT license, not the GPL one.
https://github.com/4ian/GDevelop/blob/master/license.txt

Can you make it more obvious on the page about what the limitations of that license is? In those terms, kaboom is still a great engine for educational purposes, just not very good for any indie commercial work.

Of course you can also change the license itself, but I imagine this is a decision to be taken by replit who owns the engine.

**Comment by slmjkdbtl** [comment]
Will definitely think about license issues I'll discuss with the team. Will respond here later 🙏

**Comment by triptych** [comment]
I want to make a tool which generates KaboomJS games. But I'm hesitating because of the License. Having something like MIT would make a difference in adoption IMHO.

**Comment by blurymind** [comment]
The licenses poses a block to adoption as it is now, but perhaps the authors will consider adopting the mit license or any other non viral open source license?

**Comment by amasad** [comment]
You bring up good points.

**Comment by slmjkdbtl** [comment]
65162ae

**Comment by blurymind** [comment]
@slmjkdbtl Thank you!

**Comment by triptych** [comment]
WOW this is huge! Thank you  SO MUCH!

**Comment by kgish** [comment]
Excellent, thanks a MILLION!

**Comment by ex** [comment]
thank you very much
