### ISSUE TITLE
Assign a new position to object

### ISSUE THREAD

**Issue by simhox** [replit/kaboom#106]
Hello,

What i would like to do is, is to assign a new position to an object, player when pressing a certain key.

I tried with player.pos.add({x,y}) but that didnt to anything.

Version used is 0.51. 

Thank you very much,

**Comment by slmjkdbtl** [comment]
Hi. `vec2.add()` returns a new vec2, won't mutate the existing. You can do`player.pos = player.pos.add()`, or `player.pos = vec2(x, y)`, or `player.move(speedX, speedY)`

**Comment by simhox** [comment]
That was what i needed. Thank you
