### ISSUE TITLE
Splashcreens

### ISSUE THREAD

**Issue by lajbel** [replit/kaboom#112]
I have been able to add splashcreens to my kaboom games using rgba and images, but a helper would be good to be able to put several splash screens and have them displayed after the loader, before loading the initial scene

**Comment by slmjkdbtl** [comment]
What kind of features are you thinking for the helper to do? Splash screens can be as simple as this:
```js
scene("splash", () => {
    wait(2, () => go("game"));
});
```

**Comment by lajbel** [comment]
I was referring to automatic ones like godot has, and others, that you simply put the image and they are in charge of making it appear and disappear, with an opacity transition. Yes, it can be done perfectly only with what already exists (I myself have it like that) but a function to facilitate it would be good, for newer people

**Comment by slmjkdbtl** [comment]
Gotcha, could be a good idea for a plugin, maybe something like
```js
splash(
    images: string[],
    startScene: string,
    time: number,
    transition: number,
);

splash(["img1", "img2"], "game", 2, 0.5);
```
?

**Comment by lajbel** [comment]
Yes! I will try to make a plugin like this
