### ISSUE TITLE
Adding position to player leads to collision

### ISSUE THREAD

**Issue by simhox** [replit/kaboom#113]
Hello again, 

i'm currently setting the postion of a player object via 

` player.pos.add({x:10,y:50}); `

and then it can happen that the player collides with a  wall/solid object or is stuck in there.  Ideally there would be a lookup  wether i would collide with a certain object already beforehand but to keep things simple I'm currently  using 

`
    k.action("wall", (t) =>
    {
        if (player.pos.dist(t.pos) <= 32)
        {
          //logic
        }
}
`

Is there an easier solution to prevent the the player colliding into a wall? 

Maybe the easiest solution would be to have a dist lookup that goes into a certain direction or area like 

```
        if (player.pos.distInDir(t.pos, vec2(2,4) ) <= 32)
        {
          //logic
        }
```

I know this might be a feature request but happy to hear your thoughts on this. 

Version used is  0.51

BR,

**Comment by slmjkdbtl** [comment]
If the object has the `area()` component (which exists by default if it has `sprite()`, `text()` or `rect()`), it'll have a `resolve()` component which checks every `solid()` objects in the scene and push that object out of those

so
```js
player.action(() => {
    player.resolve();
});
```
will make sure the `player` will never overlap with any objects with `solid()` component

also note that `resolve()` will be renamed to `pushOutAll()` in the next version release
