### ISSUE TITLE
I believe the dot product for vectors is wrong

### ISSUE THREAD

**Issue by hitsthings** [replit/kaboom#117]
Lemme start by saying I am by no means a game developer or math whiz!
But I think the logic for dot product is wrong. It is `x1*x2 + y1PLUSy2` whereas I believe it should be `x1*x2 + y1*y2` . A `*` was typo'd as `+`
https://github.com/replit/kaboom/blob/4925fd04b764686c3f27acfa4bbf89c29801352a/src/math.ts#L99

Unrelated (I've noticed you don't respond to these issues) - I'd really love if the license were switched to MIT. As it stands, I will likely migrate away from kaboom after today to keep my options open before I get too invested. Just a data point for you.

Take care, and thanks for the fun so far!

**Comment by kgish** [comment]
Just out of curiosity, why do you consider GPL bad for your purpose?

**Comment by hitsthings** [comment]
I'd like to keep the option open of selling a game instead of giving it away. My understanding is that if my game uses a GPL library, I'm required to license it under GPL which would allow anyone to legally distribute the game for free, which wouldn't be great for sales.

**Comment by slmjkdbtl** [comment]
Nice catch! A typo indeed, fixed in 5d9b32a
