### ISSUE TITLE
Animation Presets for sprites

### ISSUE THREAD

**Issue by jdiperla** [replit/kaboom#119]
I am looking at the drive example. 

So it seems this code loads up the spritesheet and slices it into 3 sprites going vertically. 

```
loadSprite("car", "img/car.png", {
	sliceX: 3,
	anims: {
		move: {
			from: 0,
			to: 1,
		},
		idle: {
			from: 2,
			to: 2,
		},
	},
});
```

Based on the example, the spritesheet is 81 pixels. Divided by 3, the car frame is then 27 pixels.  Frames 1 and 2(Or going by index 0 and 1 in the code) is the frame that animates the moving car and idle is frame 3 (or index 2). 

This next code creates the car object using the car sprite above:
```
const car = add([
	sprite("car"),
	pos(24, height() / 2),
	color(),
	origin("center"),
	area(vec2(-12, -6), vec2(12, 8)),
	{
		speed: 120,
	},
]);
```

The function below then sets the car's current animation:
`car.play("move");`

While this can stay in place for broader control, I was hoping we could make a control set that would automate animation a bit more with less coding involved. We can leave nims in place, but also add this automated tag for defaultAnims, like so:

```
loadSprite("car", "img/car.png", {
	sliceX: 3,
	defaultAnims: {
		left: {
			from: 0,
			to: 5,
		},
                 right: {
			from: 6,
			to: 10,
		},
                 up: {
			from: 11,
			to: 15,
		},
                 down: {
			from: 16,
			to: 20
		},
                 upleft: {
			from: 21,
			to: 26,
		},
                 upright: {
			from: 27,
			to: 31,
		},
                 downleft: {
			from: 32,
			to: 37,
		},
                 downright: {
			from: 38,
			to: 43,
		},
		idle: {
			from: 44,
			to: 44,
		},
		death: {
			from: 45,
			to: 47,
		},
		hitcolide: {
			from: 48,
			to: 52,
		crouch: {
			from: 53,
			to: 58,
		},
		jumpleft: {
			from: 59,
			to: 63,
		},
		jumpright: {
			from: 64,
			to: 68,
		},
		},
	},
});
```

Then you can use anims for custom animations and you wouldn't need to set car.play all that often just to change animations.

**Comment by slmjkdbtl** [comment]
Sorry I'm not fully understanding, what's the desired behavior for anims specified in `defaultAnims`?

**Comment by jdiperla** [comment]
Actually, you can ignore this. I had a "duh" moment. and figured out what I was trying to do. LOL. Sorry.
