### ISSUE TITLE
Dragging object

### ISSUE THREAD

**Issue by reflog** [replit/kaboom#12]
Hi! Kaboom looks amazing!
Is there any support for dragging an object?
I found event handlers for click and hover, but not for dragging.

**Comment by slmjkdbtl** [comment]
Thanks!

I'll make an example for that in a min, will post on this thread when it's there

**Comment by slmjkdbtl** [comment]
There's an drag & drop example here now: https://kaboomjs.com/examples#drag

**Comment by slmjkdbtl** [comment]
the example above should demonstrate how to implement basic drag & drop behavior, feel free to reopen for more question, bugs, or proposal for a better way of doing it
