### ISSUE TITLE
Document which methods each component provides

### ISSUE THREAD

**Issue by amundo** [replit/kaboom#121]
It took me a while of digging through various tutorials to figure out that to use `.flipX()` you have to include the `scale` component. 

Could this kind of info be added to the component docs? For instance, it could have a “methods” section that describes what methods the component makes available.

Also, I would be happy to help do this work.

<small>PS Kaboom is the 💣 </small>

**Comment by slmjkdbtl** [comment]
Sorry the docs are still a bit incomplete!

Also `flipX()` on `scale` was kinda temporary, in the upcoming version it actually becomes a method under `sprite()` which is actual texture flipping instead of scaling negatively. I'll add them to the docs before the release.

**Comment by triptych** [comment]
Having a set of docs that aren't just the ones on the kaboomjs home page would be awesome - those are great for getting started but not so great for referencing day to day.

**Comment by kgish** [comment]
:+1:

**Comment by slmjkdbtl** [comment]
Update: Planning to try out directly generate typed docs with stuff like [typedoc](https://typedoc.org/), better suggestions are welcome.

**Comment by slmjkdbtl** [comment]
The new doc now have types for all components (e.g. [SpriteComp](https://kaboomjs.com/doc#SpriteComp)). Description for each field coming soon.
