### ISSUE TITLE
Enable normal fonts? 

### ISSUE THREAD

**Issue by amundo** [replit/kaboom#122]
Would it be possible to enable non-bitmap fonts in text? 

I know it’s possible for canvas, but I haven’t looked into your implementation:

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text

I have always wanted to try making a game where the "sprites" are emoji!

**Comment by slmjkdbtl** [comment]
Kaboom rendering is based on WebGL, using truetype / opentype fonts in WebGL requires bit of a hustle and probably need external dependencies to parse them. I also would really like to have them but unfortunately it's not the biggest priority at the moment, will definitely support in the future.

**Comment by amundo** [comment]
Okay, retro is cool too ;)

**Comment by slmjkdbtl** [comment]
Thanks for understanding!

**Comment by slmjkdbtl** [comment]
Did a bit of research and this might be an easier implementation that can be done in near future:

1. use [`FontFace`](https://developer.mozilla.org/en-US/docs/Web/API/FontFace) API to load the font
2. draw the font on another offscreen `<canvas>` with 2d ctx 
3. use that offscreen canvas as a WebGL texture and draw it

**Comment by slmjkdbtl** [comment]
It's implemented on master and `kaboom@next`, see new examples/font.ts
