### ISSUE TITLE
Dynamic rescale 

### ISSUE THREAD

**Issue by lajbel** [replit/kaboom#124]
Rescale canvas according to the available space like phaser or other html game engines

**Comment by slmjkdbtl** [comment]
Do you mean something like `kaboom({ fullscreen: true })`?

**Comment by lajbel** [comment]
Fullscreen only grabs the width and height of the page and uses them in the values ​​for the creation of the canvas, but don't rescale it

**Comment by slmjkdbtl** [comment]
Do you mean resize the canvas when window resizes, or something like stretch the game view to scale to window size?

**Comment by lajbel** [comment]
I will refer more to scaling the content, which is enlarged (without modifying anything in the game), it would be like the `kaboom({scale: 2})` property but automatic according to the width of the space provided

**Comment by slmjkdbtl** [comment]
Gotcha, this is something I'm working on atm, there's now a [`scaleMode`](https://github.com/replit/kaboom/blob/8596deea265b8324fb53705ac830024fdf6f8129/src/types.ts#L222) option (can try out on `kaboom@next`)

```js
kaboom({
    scaleMode: "stretch",
    width: 320,
    height: 240,
    fullscreen: true,
});
```

if you specify you game's `width` and `height` and `scaleMode: "stretch"`, it'll stretch everything to the canvas size. Also working on a `"letterbox"` mode which will preserve aspect ratio and leave black bars on side for extra space, but that's not fully functional yet. If left out or `scaleMode: "none"` it'll not scale anything just make the canvas bigger.

**Comment by lajbel** [comment]
Cool! I have seen it in the commits, but I was waiting for you to document it or say how it works to test it, right now I will, thanks

**Comment by slmjkdbtl** [comment]
Will document when it's good to release!

**Comment by lajbel** [comment]
Added in `@next`

Whoops this is my issue
