### ISSUE TITLE
npm version older than  latest release ver

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#125]
Latest version on npmjs https://www.npmjs.com/package/kaboom -- 0.5.1
Latest version on package.json-- https://github.com/replit/kaboom/blob/master/package.json -- 0.6.0

I understand it's not ready for a npm push - just posting as a reminder.

**Comment by slmjkdbtl** [comment]
Yeah, actually going to publish the new version tomorrow!

**Comment by kgish** [comment]
Hurrah!

**Comment by slmjkdbtl** [comment]
sorry i lied.. was moving some code around + cleaning, got some typescript issues and hope to clear them before release 🥲

**Comment by triptych** [comment]
Can't wait! I want to update all my Observable demos and work on something new. Awaiting NPM push to get the latest code.

**Comment by slmjkdbtl** [comment]
You guys can use `kaboom@next` now which will be a very frequent beta release. Really want to clean up all existing problems before the official minor version release.

**Comment by triptych** [comment]
Verfied! I can pull it down on Observable now https://observablehq.com/@triptych/test-new-kaboom-js
