### ISSUE TITLE
Custom area comp no works in 0.6.0

### ISSUE THREAD

**Issue by lajbel** [replit/kaboom#126]
I do not know if it is my error but it seems that the area does not work or does not apply, I have tried with old projects to update to 0.6.0 and the same, the custom area stops working although it worked in 0.5.0

https://replit.com/@lajbel/error-area-kbm
https://error-area-kbm.lajbel.repl.co

**Comment by slmjkdbtl** [comment]
I noticed this, thanks for reporting! Will fix this before the release.

**Comment by slmjkdbtl** [comment]
(it's fixed in `0.8.0-beta.2` or `kaboom@next`)
