### ISSUE TITLE
Missing release v0.6.0 on npm

### ISSUE THREAD

**Issue by ptkdev** [replit/kaboom#128]
Is possibile have release beta or nightly with tag -beta or -nightly on npm? Only `latest` is available.

<img width="768" alt="Schermata 2021-08-19 alle 13 44 21" src="https://user-images.githubusercontent.com/442844/130063022-a3bbd051-d6f5-4be9-a60e-4d3f53026c53.png">

**Comment by slmjkdbtl** [comment]
There's still a couple problems blocking the release. Nightly build sounds 👍  I'll look into that.

**Comment by triptych** [comment]
Yes, many of us get the package from npm instead of downloading so having more granular releases would be nice!

**Comment by slmjkdbtl** [comment]
I'll be publishing beta versions under tag `kaboom@next` (the changes are usually reflected in `CHANGELOG.md` but not guaranteed on website doc)

**Comment by triptych** [comment]
I see this working now … for example https://observablehq.com/@triptych/test-new-kaboom-js
