### ISSUE TITLE
Add fonts question 

### ISSUE THREAD

**Issue by lajbel** [replit/kaboom#129]
What would be the way to add the following font to Kaboom?

![image](https://user-images.githubusercontent.com/71136486/130164349-16db134d-def1-4d57-81ce-83eba0d60b1e.png)

I try with `loadFont("ponger", "./fonts/ponger.png", 13, 8);` but no works

**Comment by slmjkdbtl** [comment]
There's no way to add this particular font, kaboom uses monospace bitmap font (for this one there's no way to know each character's position / size and they're not all 13x8)

But adding truetype / opentype fonts is planned, see #122

**Comment by lajbel** [comment]
Okay! Thanks
