### ISSUE TITLE
Stop an action/collision detection 

### ISSUE THREAD

**Issue by simhox** [replit/kaboom#130]
Hello :)

Is there a possibility to stop an action / collision detection again? I only want to use the collision detection and then do something once i collided but i dont want the expensive collision detection to keep runnning. Is there a workaround/solution for this? 

Generally this is needed for pathfinding possibilities in an rpg. I have seen that there is a feature being planned for grid based rpg development. Would be nice if pathfinding could considered when building this. 

 Thanks alot for your work btw, generally love working with the lib. 

Best regards,

**Comment by joshuacurtiss** [comment]
Could you have collision detection based on a tag on the entity and then remove the tag when the event happens?

**Comment by simhox** [comment]
Thank you for your suggestion. Its a great idea yet unfortunatly i couldn't get it to work. 

Also I think it won't work in my case as i want to basically only check once(with all wall tiles) and in either case stop the checking for collision independent of wether the collision happens.

**Comment by slmjkdbtl** [comment]
There's the function `isCollided(obj: GameObj): boolean` that checks one time, is that what you're looking for?

**Comment by slmjkdbtl** [comment]
In addition, if you're using `kaboom@next` all events like `action` will return an `EventCanceller`, which is a function that removes the event

```js
const rmAction = action("obj", () => {});
rmAction(); // will remove that action above
```

but I think `isCollided()` might fit your case better

**Comment by simhox** [comment]
Somehow my answer wasnt sent of last time,but what i wanted to say is yes ` isCollided(obj: GameObj): boolean` works perfect for me as i can just iterate the objects i need. Thats super convinient 👍 Thank alot for your answers everybody :) 

Really happy about the event cancellation possibility, that should give more control about the whole action management. Thanks for that as well 👍 .
