### ISSUE TITLE
Question about kaboom versions

### ISSUE THREAD

**Issue by lajbel** [replit/kaboom#132]
I've been seeing the progress of the project, my congratulations to tga, it's a great engine, but I have a question Why the changelog versions skip the 6.0 and 7.0, is something strange, in a week it has been changed version about three times

**Comment by slmjkdbtl** [comment]
I'm not very familiar with npm and those version were mistakenly published. When 0.6 was published I noticed a very obvious bug so immediately unpublished. 0.7 was mistakenly published due to some confusions with npm release tags. Sorry for the confusions!
