### ISSUE TITLE
Kaboom website is down

### ISSUE THREAD

**Issue by learnuidev** [replit/kaboom#135]
<img width="1366" alt="Screen Shot 2021-08-22 at 8 49 04 AM" src="https://user-images.githubusercontent.com/67298065/130355844-bdaddcf3-3e8f-4eee-a37f-a30c2b8d2f76.png">

**Comment by lajbel** [comment]
it may have to do with dns issues in subdomains repl.co replit

**Comment by slmjkdbtl** [comment]
I can't reproduce. Is it still a problem?

**Comment by lajbel** [comment]
> I can't reproduce. Is it still a problem?

If the kaboom site was hosted on replit, I would think it would be fixed.

**Comment by slmjkdbtl** [comment]
Yeah it's hosted on replit, so is the website still down on your end?

**Comment by lajbel** [comment]
> Yeah it's hosted on replit, so is the website still down on your end?

No, it should already work, it is that recently, replit had DNS problems with the sites hosted on the web, but it is already solved!

**Comment by slmjkdbtl** [comment]
Hmm yeah some times it does have some DNS problem, glad it's up by now!
