### ISSUE TITLE
pausing or stopping sound does not work when loop is true

### ISSUE THREAD

**Issue by ericjung** [replit/kaboom#15]
Pause does not work, even in the example:
https://kaboomjs.com/examples#audio
I tried in my own game with the same result. I have background music that I want to pause or stop when the game is over. Is there a work-around for now?

**Comment by ericjung** [comment]
Nevermind. I was using 0.1.x. After upgrading to 0.2.0, pause() and stop() both work. However, I think the examples should be updated to use a more recent kaboomjs version so this feature works in the examples.

**Comment by slmjkdbtl** [comment]
Yeah! Sorry they're not live updated, it will be improved in the future. Also 0.2.0 is not officially released yet, there's a change to have breaking change between now and the official 0.2.0
