### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by mktcode** [replit/kaboom#151]
I'm trying kaboom.js for the first time and I have a simple scene with a level.

```javascript
import './style.css'

kaboom({
  fullscreen: true,
  global: true
})

loadSprite('tiles', './tilemap.png', {
  sliceX: 3,
  sliceY: 1
})

scene('main', () => {
  const map = [
    '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    '@                                                                          @',
    '@                                                                          @',
    '@     @                                                                    @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@                                                                          @',
    '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
  ]
  
  const tileSize = 32
  const level = addLevel(map, {
    width: tileSize,
    height: tileSize,
    '@': [
      'wall',
      sprite('tiles', { frame: 0 }),
    ],
    ' ': [
      sprite('tiles', { frame: 1 })
    ]
  })

  action(() => debug.log('FPS: ' + debug.fps()))
})

go('main')
```

![ezgif-7-82dcf060ba00](https://user-images.githubusercontent.com/6792578/130970320-e65a5be1-d507-4b86-8fca-1a2ca44564bd.gif)

The bigger the level the lower the fps.
I'm working on an slow office laptop but performance should be better than this I think. Anything I can do about this? Or is kaboom just not optimized that much yet?

**Comment by joshuacurtiss** [comment]
I'll just remark on a related note that I've noticed processor working extremely hard as I develop. Often I'm working on games on an Intel MacBook air just on my couch as I relax in the evening and I'll notice the laptop get very hot with the fan indicating high utilization just in "normal" use (even when not playing but if the game's background processes are running). Not complaining but just noticing this confirms that a performance audit at some point sounds good!!

**Comment by slmjkdbtl** [comment]
That's very weird, kaboom is fairly light. Are you having similar issues with other browser game making tools?

**Comment by joshuacurtiss** [comment]
I was actually thinking to myself that I made a relatively more sophisticated game in Phaser 3 and never had my fan turn up at all I don't think. The Kaboom game I'm doing is basically a bomberman clone so pretty simple motion/collision detection. I was surprised but chalked it up to just inefficiencies that just need to be ironed out.

**Comment by slmjkdbtl** [comment]
Hmm I'll investigate. Is the game also running slow when the fan hits?

**Comment by slmjkdbtl** [comment]
Also would like to see the code if possible, any chance you are registering some per-frame events every frame?

**Comment by joshuacurtiss** [comment]
No, although I do have a block like this, which I thought was necessary for player rendering? 
```js
player.action(() => {
    player.resolve()
})
```

**Comment by slmjkdbtl** [comment]
`resolve()` doesn't do anything with rendering it checks collision between every obj with `solid` on them and pushes player out if they collide, can be very costly if there's a ton of solid objs. A common trick is to turn off solid if they're very far from user and impossible to collide
```js
action("block", (b) => {
    b.solid = player.pos.dist(b.pos) <= 20;
});
```
That's a confusing name yeah, it's renamed to `pushOutAll()` in upcoming version

**Comment by joshuacurtiss** [comment]
Hmm interesting.  Given that my game is a bomberman clone and all of the blocks and bombs are solids, there's a lot of collision checking i guess. It's really more efficient to check all the blocks' position to the player on every frame? I can try implementing that..

**Comment by oaklandgit** [comment]
FWIW my experience is exactly as @joshuacurtiss  describes. The processor runs very hot. Happy to provide more details re my code and hardware.

**Comment by slmjkdbtl** [comment]
Yeah please provide code if possible 🙏

**Comment by oaklandgit** [comment]
Sure. See it on my repl.it here:

https://replit.com/@LarryStone/Tailpipe-WIP

**Comment by slmjkdbtl** [comment]
Are you all experiencing this inside replit editor? Does this also happen on generic browser tab?

**Comment by oaklandgit** [comment]
Yes. I had the same thought, but it happens in both environments.

**Comment by oaklandgit** [comment]
Correction: I spent some more time running my project in a generic browser tab, and I think it's actually fine. So perhaps the culprit is replit and not kaboom.

**Comment by adrianfiedler** [comment]
I also experience big frame drops when using big levels with a lot of small sprites in it. Even though they don’t have a collider or anything it goes from 60fps down to 19fps only because I add those rows in the level array.

**Comment by Zachiah** [comment]
Could it be possible to allow blocks to merge in tilemaps? Ie to provide a mechanism of specifying that certain objects should be treated as one larger object?

**Comment by thomasjwalsh** [comment]
Hey guys, had similar problem with low fps. I'm using chrome. I notice it was fast on safari and firefox. I turned hardware acceleration on for chrome and fps went up to meet safari and firefox. Maybe this helps your problem too?

**Comment by oaklandgit** [comment]
@stmn Are you using Mac OS on an M1 processor? I've found a setting on Mac OS that affects Safari performance significantly: "low power mode." For a while, I was having similar issues I couldn't track down, and then I realized it was this.

**Comment by stmn** [comment]
@oaklandgit Yes, however I have this mode disabled.

To be honest Safari is totally not my target, but I like to optimize on slower pc/browser than on faster. 
It's not important for me if I can just change z layer but I found its worth mentioning.

I stripped and simplified my code and leaved only problematic code. 
Having two objects on same "z" layer causing drops. 

https://gist.github.com/stmn/b5f782acad691964065c0a9efaeb3ce0
https://monosnap.com/file/O6uxUSIc9fBfJBFkQeuVjqJGeyRNag

**Comment by oaklandgit** [comment]
@stmn

Yeah, me too:
> To be honest Safari is totally not my target, but I like to optimize on slower pc/browser than on faster.

Everything I've thrown at Chrome has had no trouble at all, but even with the "low power mode" discovery I mentioned, Safari is still sluggish.

**Comment by lajbel** [comment]
FPS and optimization was improved so much in the unreleased new version of Kaboom, so will close this :). Thank you!
