### ISSUE TITLE
Fullscreen not working!

### ISSUE THREAD

**Issue by sina-yeganeh** [replit/kaboom#156]
Hello. I sat **fullscreen** as true but it happend:

![Screenshot_20210828080255](https://user-images.githubusercontent.com/71815150/131204994-c987320f-2ce8-4533-8ffe-ff7a167cb236.jpg)

**I used python HTTP server for handle assets.**

**Comment by slmjkdbtl** [comment]
Which version are you on?

**Comment by sina-yeganeh** [comment]
this version: https://unpkg.com/kaboom@next/dist/kaboom.js

**Comment by slmjkdbtl** [comment]
There's some changes made to the fullscreen system. Now by default the canvas will be set to the container size if no `width` and `height` are provided, with optional `stretch` and `letterbox` flags to control if the content scaling strategy. The name `fullscreen` will be reserved for the ["actual" fullscreen](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)

But what you have here looks like a bug, can you explain more what's happening? Looks like the height is being weird?

**Comment by sina-yeganeh** [comment]
Hello again. 
this is my code:
```js
export const KC = kaboom({
  global: true,
  fullscreen: true,
  debug: true,
  scale: 2,
})
```
<hr>

I try to dont set full screen. but that bug happend ...
Can you fix this issue? Becuse I am going to start project with kaboom and I need the `next` version of kaboom.

**Comment by slmjkdbtl** [comment]
Sorry I still don't understand the problem, what's the desire behavior and what have gone wrong?

**Comment by sina-yeganeh** [comment]
full screen not working 📛 
what I must do?

**Comment by sina-yeganeh** [comment]
And that is my code...

**Comment by slmjkdbtl** [comment]
Not working meaning it's not fullscreen? By default the canvas will stretch to container size, if the container (should be `document.body` in not specified otherwise). Maybe try `body { width: 100%; height: 100% }` in CSS?

Also on beta `global` and `debug` are enabled by default now and there's no `fullscreen` flag.

**Comment by sina-yeganeh** [comment]
![Screenshot_20210903092246](https://user-images.githubusercontent.com/71815150/131952257-879518c1-22f7-4667-9911-e0e17971ba29.jpg)

main javascript file:

```js
import { Main } from "./scene.js"

export const KC = kaboom({
  scale: 2,
  clearColor: [0, 0, 0, 1]
})

scene("main", Main())
```

index.html file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Space Task</title>
  <style>
    body {
      margin: 0;
      overflow: hidden;
    }
  </style>
</head>
<body>
  <script src="https://unpkg.com/kaboom@next/dist/kaboom.js"></script>
  <script src="main.js" type="module"></script>
</body>
</html>
```

❓❓❓

**Comment by slmjkdbtl** [comment]
Oh I managed to reproduce. You'll have to set both `body` and `html`
```css
html,
body {
    width: 100%;
    height: 100%;
}
```
i'll add this to the docs
