### ISSUE TITLE
Can you adjust where a player spawns in after a room transition?

### ISSUE THREAD

**Issue by Cobanz** [replit/kaboom#159]
trying to work with a platformer and got him spawning in at like top left and dropping in each room, but surely there is a way to set his spawn location on a symbol like you do all the other sprites? but when i do it i get 2 of him in a room and not just him. any ideas?

**Comment by slmjkdbtl** [comment]
Not entirely sure what you meant, you can define the player in the level ascii map, or outside with plain `add()`, or use `level.spawn()` to add spawn a symbol to existing map, either one should only add 1 by itself, are you adding multiple in you code?
