### ISSUE TITLE
Not possible to have collisions and define render order

### ISSUE THREAD

**Issue by finnp** [replit/kaboom#167]
Right now it's only possible to define render order by either adding game objects after each other or specifying layers for them (and not have collisions)

It would be good to have a way to specify this, either by allowing to specify which layers can collide with each other or provide a way to define some sort of z coordinate to define the order of rendering.

**Comment by slmjkdbtl** [comment]
What about this
```js
layers([
    "bg",
    "game",
    "ui",
]);

add([
    // pass in manual z value (0.0 - 1.0) (better range suggestion? like 0 - 1024?)
    z(0.5),
    // can also pass in a string that specifies a layer (converge with layer())
    z("ui"),
]);
```
and just ditch the logic to not check collision between diff layers since you can always just do it yourself if you want to

**Comment by finnp** [comment]
That sounds like a good API. I think the z value could be an arbitrary number where higher numbers just render further in front.

**Comment by finnp** [comment]
Ah I overread the layer part. I think maybe I would keep the layers and have the z index be the position inside the layer.

Or maybe it could be possible to assign z positions to the layers and they default to `0, 1, 2, 3`?  Seems a bit complicated though

**Comment by slmjkdbtl** [comment]
> keep the layers and have the z index be the position inside the layer

I like this 👍

**Comment by finnp** [comment]
I'm going to give it a shot at implementing this

**Comment by finnp** [comment]
Created a pull request, didn't update documentation yet: https://github.com/replit/kaboom/pull/168/files

**Comment by slmjkdbtl** [comment]
Thanks. The website is reworked and the doc should be generated if you add the `z()` into `KaboomCtx` (I added), new website will be shipped shortly.

**Comment by slmjkdbtl** [comment]
Also published this to `kaboom@0.8.0-beta.21` (or `kaboom@next`)

**Comment by finnp** [comment]
Awesome thank you! From issue reported to shipped in 9 hours 🚀 🌔

**Comment by joshuacurtiss** [comment]
Love the idea of `z()`. Like others said, layers are useful but having `z()` as an option within layer is great.  My current game has some bugs because of this issue. 

I haven't tried going beyond the 0.5.x release on npm but after all this talk in the forum I'm tempted to.... 😄

**Comment by slmjkdbtl** [comment]
@joshuacurtiss Yeah welcome to try! The changes you need to pay attention to are all in `CHANGELOG.md`. Also planning the stable release next week
