### ISSUE TITLE
Pathfinding Example

### ISSUE THREAD

**Issue by aaronjewell** [replit/kaboom#17]
Here's an example of using a third-party pathfinding library.

This was pretty intuitive to setup, feel free to use all or part of it in an example.

https://replit.com/talk/share/Pathfinding-in-Kaboom/135194

**Comment by slmjkdbtl** [comment]
This is really cool, thanks! Kaboom will have its own pathfinding one day (baked in the `addLevel` suite of interfaces), but it's great to have an example that shows it could work with outside libs

**Comment by lajbel** [comment]
There is already one added in d31538bbe18ee770e4a1fd981ba8c2f3fa8e75
