### ISSUE TITLE
Custom event "grounded" now "ground"?

### ISSUE THREAD

**Issue by nicolailebek** [replit/kaboom#182]
Hey guys!

After installing kaboom@next the "grounded" custom events didn't work anymore. 
Just took a look at the codebase to see that the custom event being triggered from body is now 'ground'.

```
player.on('grounded', () => ...) // doesn't work
player.on('ground', () => ...) // works
```

Docs say it should be 'grounded'..

**Comment by slmjkdbtl** [comment]
Hey! Sorry the docs is a bit desync now, the doc / website is being reworked (the new one is 100% generated) and will be shipped next week with a kaboom stable release. Before that please clone the repl and `npm run setup` `npm run dev` to see the latest API on `@next`, or use this temp link I just setup: https://kaboom2000.slmjkdbtl.repl.co/
