### ISSUE TITLE
how to set background image?

### ISSUE THREAD

**Issue by sina-yeganeh** [replit/kaboom#183]
Hi, I want to set background image and reapte that in X and Y.
how I can?

**Comment by lajbel** [comment]
Use the add() function as if it were a sprite!

```.js
add([
    sprite("background")
]);
```

If you want your background to take over the entire screen, make sure that the size of the image is the same size as the width() and height() of the game

(for set the sizes):
```.js
kaboom({
    width: 500,
    height: 500
});
```

**Comment by slmjkdbtl** [comment]
can also use the `tiled: true` option to make it tiled https://kaboom2000.slmjkdbtl.repl.co/demo#tiled

**Comment by sina-yeganeh** [comment]
Thank a lot 🍨
