### ISSUE TITLE
Sprite and layer transparency

### ISSUE THREAD

**Issue by ericjung** [replit/kaboom#19]
Can you add transparency to sprites and layer?

* sprite transparency: can be used to show a player or object is invincible or otherwise unaffected by collisions
* layer transparency: useful to display a high-score screen or instruction screen overlaid on the game. Currently I'm doing this with separate scenes.

This could also be covered with fadeIn()/fadeOut() animations.

**Comment by slmjkdbtl** [comment]
There's no layer transparency yet, but with `sprite()` (or `text()`, `rect()` etc.), you can pass in a `color()` component with alpha value
```js
add([
	sprite("froggy"),
	color(1, 1, 1, 0.2), // with alpha value of 0.2, and not affecting its original color
]);
```

the layer system is like tags, objects aren't store in layers, and the layer tag on an object merely affects its `z` position in render, so if we have it it'll probably be something like this:

```js
every((obj) => {
    if (obj.layer === "ui") {
        obj.color.a = 0.5; // make sure everyone already has a color()
    }
});
```
which works, but not great, cuz "layer opacity" and "obj opacity" sounds conceptually independent to each other, but actually it's faking "layer opacity" with individual "obj opacity"s

**Comment by ericjung** [comment]
Thanks for the reply; wish I could ask questions somewhere without using github issues or twitter.  Regarding color, I've been using rgb() since I did not see color() documented anywhere. And rgb() does not work as I expect -- for example:

```
  score = add([
      text("score: " + elliot.score, 8),
      pos(10, 25),
      rgb(0,255,0)
  ]);
```

shouldn't that display as green? I get white. Anyway, I'll try color() but I'm not sure how it differs from rgb(). Is there also ability to use hex color codes? By the way, if you have a way to be reached privately, i would like to show you what I've done with your lovely library. Thank you for writing it!

**Comment by slmjkdbtl** [comment]
Sorry it's a bit confusing, `rgb()` returns a standalone math object with `r, g, b, a` field, while `color()` is a component which works with the component system, similar to the difference between `vec2()` and `pos()`

Also these components also accepts the math objects as arguments as well, like `pos(vec2(x, y))`, `color(rgba(0, 0, 1, 0.5))`, you can consider taking direct values like `pos(x, y)` as a shorthand.

Also colors in kaboom works in `0 - 1` as floating point numbers, instead of `0 - 255`

**Comment by ericjung** [comment]
Thank you for the explanation.

Another question: if I have a multi-level game, and I'm using scenes for each level, how can I keep the same sprite across scenes? For example, the player sprite must exist on every level. Should I use something besides scenes for this? Or should I create the player sprite on every scene?

**Comment by slmjkdbtl** [comment]
You can do something similar to [this wip example](https://kaboomjs.com/examples#rpg) here, where you pass arguments to scene with `go("scene", args)` or `start("scene", args)` (in this case passing the level to load), so using the same scene for similar game layouts but customized with arguments

**Comment by ericjung** [comment]
Thank you.

Two more questions:

1. What is the easiest way to prevent player from moving off the top/bottom of the screen? I have code like this for moving up/down:

```
  keyDown("up", () => {
      if (paused()) {
          return;
      }      
      if (player.pos.y < 1){
          player.pos.y = 1;
      }
      else {
        player.pos.y = player.pos.y-20;
      }     
  });

  keyDown("down", () => {
      if (paused()) {
          return;
      }      
      if(player.pos.y < height()){
          player.pos.y = player.pos.y+20;
      }
      else {
        player.pos.y = height()-20;
      }      
  });
```

The problem is the player "jumps" back when he hits the top or bottom. He is pushed back 20 pixels making things look jittery, rather than just stopping and not moving anymore in that direction. I can show an example in action if you want.

2. My full-screen looks just a little larger than full-screen. So the top and bottom are clipped and user has to scroll up/down just a little bit to see everything. Looks like maybe 5-10 pixels are clipped on the top/bottom. Any ideas?

If it is easier to see what I mean please visit http://ericjung.net/sardines but know this is still a work in progress!

**Comment by slmjkdbtl** [comment]
1. try
```js
player.pos.y -= 20;
if (player.pos.y < 0) {
    player.pos.y = 0;
}
```
cuz if at the current frame the player's pos y is `2`, it'll perform the `- 20` calculation and make it negative and out of screen. Also maybe consider multiplying the speed by `dt()`, or use `.move()`, to make the player move at constant speed / unaffected by frame rate (if not the player will move faster at faster frame rate)

2. weird, inspecting shows that the `body` has a `margin: 8px`, is that anywhere in the code?

P.S.
loving the vibe of you game!

**Comment by ericjung** [comment]
> cuz if at the current frame the player's pos y is 2, it'll perform the - 20 calculation and make it negative and out of screen.

It is still not smooth, please take a look.

> Also maybe consider multiplying the speed by dt(), or use .move()

Yes, I tried this, but this functions are not well-documented. I do not know what the arguments are. For example, [in the docs](https://kaboomjs.com/) I see it used different ways:

Two arguments
```
// move an object by a speed (dt will be multiplied)
obj.move(100, 100);
```

One argument
```
player.action(() => {
    player.move(player.dir.scale(player.speed));
});
```
Is it (x,y) coordinate?

> weird, inspecting shows that the body has a margin: 8px, is that anywhere in the code?

No. Looking at dev tools, it is somehow in the default browser style (user agent stylesheet):

![image](https://user-images.githubusercontent.com/5875610/115050148-af685500-9e98-11eb-8cad-c9acd60676ee.png)

I tried in both Firefox and Chrome with same problem -- even though Firefox does not show the 8px margin as far as I can tell. can you think of a workaround? To shrink the fullscreen by a little bit?

**Comment by slmjkdbtl** [comment]
```html
<style>
body {
	margin: 0;
}
</style>
<script src="https://kaboomjs.com/lib/0.2.0/kaboom.js"></script>
<script type="module">

kaboom.global();

init({
	fullscreen: true,
});

scene("main", () => {

	const player = add([
		pos(0, 0),
		rect(120, 120),
	]);

	const SPEED = 1200;

	keyDown("up", () => {
		player.move(0, -SPEED);
		player.pos.y = Math.max(player.pos.y, 0);
	});

	keyDown("down", () => {
		player.move(0, SPEED);
		player.pos.y = Math.min(player.pos.y, height() - player.height);
	});

	keyDown("left", () => {
		player.move(-SPEED, 0);
		player.pos.x = Math.max(player.pos.x, 0);
	});

	keyDown("right", () => {
		player.move(SPEED, 0);
		player.pos.x = Math.min(player.pos.x, width() - player.width);
	});

});

start("main");

</script>
```

try pasting this example in a html file, the bound check should work (it's the same as I posted above except using min / max shortcut), and have to give it a `body { margin: 0 }` to disable the default margin, it'll might be too rude to change the style of anything except the canvas in the library, not sure if there's a way to get around elegantly 🤔 

oh yeah `move()` takes either a single `(vec2)`, or directly `(x, y)` as a shortcut, I'll make it clearer in the docs

**Comment by ericjung** [comment]
Hi,

Thanks for that. It really helped.

I'm stalled at making my multi-level game. It is very, very close. The problems is that keyPress() and keyDown() are not working on 2nd level. I am using same scene for multi-level, just destroying sprites and recreating them for each level. Ultimately I will have different sprites in different levels, but for now all sprites are the same on all levels.

Can you try it? Get to level 2 with 500 points for now (very easy, just 5 sardines). Then you will see level 2 start and up/down/right/left keys are not firing.

http://ericjung.net/sardines

**Comment by ericjung** [comment]
> The problems is that keyPress() and keyDown() are not working on 2nd level

I got it working. Not a bug in your code. Sorry. I have other problems now, but if they are bugs with kaboom I will try to make a minimal test case.

**Comment by slmjkdbtl** [comment]
👍 let me know if there's other issues

**Comment by slmjkdbtl** [comment]
Hi! I'm assuming this is idle and will close this for now, feel free to reopen if you have any follow up questions!
