### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by benjaminniess** [replit/kaboom#2]
Hello there,

Lovely idea you had! I was hopping to try the demos but I fugured out you've added an extra "?" here https://github.com/replit/kaboom/blob/master/src/kaboom.js#L2940

Thanks for your work I'll give it a go soon!

**Comment by rish** [comment]
I think you are referring to optional chaining:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by slmjkdbtl** [comment]
Hi! 

Is it breaking? [Seems like](https://caniuse.com/mdn-javascript_operators_optional_chaining) it's supported in all browsers starting 2020 so I just used it, but I'm thinking about introducing a build system and typescript to kaboom with esbuild and might get that polyfilled.

**Comment by benjaminniess** [comment]
Hi,

I was ignoring this syntax and yes, it seems to be supported by all updated browsers. With the latest version of chrome it's now fine but yes I was getting a white page with this error in the console and just removing the "?" solved everything so it's up to you if you want to leave it or not.

Thanks to both of you
