### ISSUE TITLE
Don't Like new home page! How can I get access to previous version?

### ISSUE THREAD

**Issue by unclecode** [replit/kaboom#202]
Hello, I like the old homepage. Especially the way you organize all the features. I keep checking and all of a sudden everything changes! Can you give me access to the previous version? And the new docs don't show some features like "addLevel".

**Comment by slmjkdbtl** [comment]
You can access the old one here https://kaboomold.slmjkdbtl.repl.co/ . The new one is still a WIP, organizing by section is coming this week! I'll add the `addLevel` one right now.

**Comment by unclecode** [comment]
Hello. thank you for the reply. And yes, I found out it was still WIP. I'm very interested in the paradigm you used in Kaboom. I run an EdTech company that teaches kids how to code. We find your setting is suitable for our course. We would like to know how we can support or sponsor your project and the customization possibilities for our platform.

**Comment by unclecode** [comment]
BTW, I think you should keep the pixelated style for now. I checked your new demo and found that there is no such thing as pixelated style. I can see this on your website or on the Kaboom video too. This is of course my personal opinion. I really like Kaboom. Good job.

**Comment by slmjkdbtl** [comment]
Yeah the official demo are mostly using some vector-style graphics now, but kaboom doesn't stop you from using pixelated graphics in any way.

I'm getting paid by Replit to develop Kaboom at the moment so currently not in need for sponsor, but curious to know what kind of customizing possibility you're thinking about?

**Comment by unclecode** [comment]
Hello. As mentioned earlier, we are an EdTech company that teaches children and adolescents computational thinking and computer programming. We have around 20,000 users and all age groups from 4 to 18 years old. One of the most effective ways is definitely to teach game development. We used various frameworks such as PhaserJS, Unity3D, or GODOT.

We became interested in KaboomJS because of its simplicity and abstraction power. This gives us a foundation for programming in JavaScript and makes developing games for kids fun. We offer you to create and maintain a new distribution of KaboomJS for our company, apply the necessary changes and structures, and maintain the framework.

We are interested in offering 3 versions for each age group. For teens (> 12) similar to KaboomJs v0.5.0. The second version is aimed at children between the ages of 9 and 12, which are less complex. I've seen adding some new components like "move()" for example. For teens (> 12), we ask them to implement the logic, but for those under 12, they prefer to use these components. Another example would be "infinite scrolling" for a background that could have components for that age group. Likewise, we would like to add more components to abstract some common complex game development tasks for this age group.

And finally, we want to make a "blocky" version for KaboomJs using Google's open-source Blockly Engine. We will use this for students under the age of 9.

This is an opportunity to help many children in our community and around the world, using frameworks like KaboomJs as a stepping stone.

I suggest that we arrange a meeting and continue to discuss.

**Comment by patrickscoleman** [comment]
Hey there! We'd be up for a call. Can you email patrick@replit.com and tiga@replit.com with some times you're free next week and we'll schedule something?

**Comment by unclecode** [comment]
Awesome. We will ask one of our team members to organize this meeting. She will contact you soon.
