### ISSUE TITLE
Change Sprite dynamically

### ISSUE THREAD

**Issue by JOKeRiino** [replit/kaboom#204]
In the old docs there was this function:
```
// could change sprite for anim if you don't use spritesheet
obj.changeSprite("froggy_left");
```
But it doesn't seem to work as of now. What is the best workaround?

**Comment by slmjkdbtl** [comment]
Now it's `obj.use(sprite("froggy_left"))` to replace the sprite component.

**Comment by JOKeRiino** [comment]
Tysm! I was building a day-night-cycle and creating and hiding multiple elements was a pain!
