### ISSUE TITLE
Is there still a way or workaround to using the "overlaps(a,b)" function?

### ISSUE THREAD

**Issue by JOKeRiino** [replit/kaboom#207]
Scenario: One obj has health. If another obj overlaps with it, the health depreciates until the object dies.

**Comment by joshuacurtiss** [comment]
Give the one obj a tag like `can-get-damage` and the other object a tag like `inflict-damage`, then use overlaps function, why would you want to avoid using it out of curiosity? 

You could have a check on the `action` of the object as well.

```
player.collides('inflict-damage', ()=>{
  // do stuff
})
```

**Comment by slmjkdbtl** [comment]
`overlaps` is converged with `collides` due to the change to the collision resolution system, is there any case `collides()` doesn't work to your needs?

**Comment by JOKeRiino** [comment]
This seems to work: 
`        action("f", (f) => {
            f.collides("g", (g) => {
                //console.log(g); -> reduce health
            })
        })`
But now the .collides isn't at root level.
But this doesnt create the same result:
`        collides("f","g", (f,g) => {
            console.log(g); -> reduce health
        })`
My problem is that I want to reduce the health of g WHILE it collides with f. Not EVERY TIME it collides with f.

**Comment by slmjkdbtl** [comment]
Ooh I see what you meant, you can do

```js
action(() => {
    for (const d of get("danger")) {
        if (player.isColliding(d)) {
            reduceHealth();
            break;
        }
    }
});
```
this'll `reduceHealth()` every frame when they're in contact, or you can use `loop()`, or setup your own timer.

**Comment by JOKeRiino** [comment]
```        loop(.2, () => {            
            for (const g of get("goal")) {
                if (fuel.isColliding(g)) {
                    g.life--;
                    console.log(g.life);
                    break;
                }
            }
        });```
so this is the function I am using now and it works as intended so thank you for that!
Sadly this also produces a bug. For this mechanic, I add sprites to the game that are deleted right after the "minigame" is won. But the minigame can be triggered again. Every second or third time the minigame is started (and the sprites are generated) the method above recognizes a collision even tho the two sprites are visibly not colliding. Am I missing something?

**Comment by slmjkdbtl** [comment]
Sounds weird. Are you able to provide the code, or a minimal reproducible example?

**Comment by JOKeRiino** [comment]
That's because it is - or rather was. Because I got it to work. Don't ask me how... As of right now, I don't know either.  I will update if I find out.

**Comment by slmjkdbtl** [comment]
Cool!

Can you open another issue if you find out the problem? The OG issue is resolved I think.
