### ISSUE TITLE
Animations set to 0 cause anim not found error

### ISSUE THREAD

**Issue by acousticseagull** [replit/kaboom#208]
Example:

k.loadSprite('player', 'sprites/player.png', {
    sliceX: 3,
    anims: {
      idle: 0,
      left: 1,
      right: 2
    },
  });

k.keyRelease(['left', 'right'], () => {
    player.play('idle');
  });

When the left or right key is released I get the "error: anim not found: idle."

**Comment by slmjkdbtl** [comment]
Nice catch! Fixed in master and `2000.0.0-beta.17`
