### ISSUE TITLE
Error: app.canvas.requestFullscreen is not a function, when call fullscreen()

### ISSUE THREAD

**Issue by KusStar** [replit/kaboom#213]
## Description
It occurs when I use fullscreen() in some browsers like Safari, both on MacOS and iOS.
Seems the Fullscreen API in some browser engines should have prefix, such as `webkit`, `moz`, `ms`.
If you need, I could create a PR for it. 

## References:
- [Fullscreen_API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)
- [sindresorhus/screenfull.js](https://github.com/sindresorhus/screenfull.js)

**Comment by mannysz** [comment]
@KusStar please check if #234 soles your problem.
It solved for me under a Safari experimental build.

I would appreciate if you could also help me test in MS Edge and Firefox.

**Comment by KusStar** [comment]
I run the code on stable Safari, it solved.
Also, I test it on stable FireFox and MS Edge, it works perfectly.
Thank you for your work.

**Comment by slmjkdbtl** [comment]
@KusStar Did you get it working on stable Safari? `webkitRequestFullscreen` doesn't do anything to me on Safari 14.1 🤔

**Comment by KusStar** [comment]
Sorry, I'm still using Catalina so my stable Safari is 13.1, it actually works.
But I test on Safari 14.1, it does't do anything.

**Comment by mannysz** [comment]
I think the new Safari update broke the Fullscreen API compatibility. I will investigate a bit more.

**Comment by mannysz** [comment]
Okay, I just confirmed.

- It works on all Safari 13 variants.
- Compatibility was broken on Safari 14.1+
- Compatibility is also broken on Technology Preview 15+.

With that said, it works perfectly on Google Chrome.
Considering the poor support on iOS Safari, I don't think there's much we can do other than waiting for Apple to fix it.

I filed a bug report to the Safari Team.

**Comment by slmjkdbtl** [comment]
@mannysz Thanks for doing the research, it's very weird this is broken on such a major browser.

But [p5.js's fullscreen](https://p5js.org/reference/#/p5/fullscreen) seems to work on my Safari 14.1, [their code](https://github.com/processing/p5.js/blob/43eccc78c2bae4747e7f0011f9f6d39964e20751/src/core/environment.js#L628-L646) is very similar
