### ISSUE TITLE
odd behavior from destroyAll()

### ISSUE THREAD

**Issue by acousticseagull** [replit/kaboom#214]
if you have sprites that use the health() component calling destroyAll('health') will remove them from the game.

**Comment by slmjkdbtl** [comment]
Yeah. Tags are just empty components, they're the same thing. Each component has an `id` field which act as their "tag"

**Comment by slmjkdbtl** [comment]
Actually would like to hear opinions on this one: should tags and components be the same thing, or is it better to separate them? Sometimes I think tags are more used for one-off game-specific logics, while components are often very general behaviors.
