### ISSUE TITLE
mouse position breaks on fullscreen

### ISSUE THREAD

**Issue by slmjkdbtl** [replit/kaboom#222]

**Comment by paulers** [comment]
Not sure if this issue refers to the fact that when setting `stretch: true` , the actual mouse interactive area remains within the bounds of height/width set in KaboomConf. Is that correct?

**Comment by slmjkdbtl** [comment]
Possibly, `stretch` is possibly bugged too, I'll visit that when fixing this issue!

**Comment by slmjkdbtl** [comment]
Should be fixed in #490 and published in `v2000.2`
