### ISSUE TITLE
How to clear the loop & wait

### ISSUE THREAD

**Issue by artiely** [replit/kaboom#242]
How to clear the loop & wait,I didn't find it in the document，tks!

I have many elements generated through wait and loop, but I hope to destroy them at some point, and I don’t know how to achieve it.

**Comment by lajbel** [comment]
Hi, I recommend that you use the forums to ask questions!

if you are using kaboom 6.0 or 2000, you can do the following:

```.js
const cancelMove = loop(1, () => {
    player.move(25, 0);
});

wait(2, () => cancelMove());
```

Currently you cannot with wait but I would not understand in which case you would need that, in any case you can do the following:

```.js
const waitTime = 10;
const time = 0;

action(() => time += dt())

const cancelWait = action(() => {
    if(time >= waitTime) {//...}
});
```
You can also check https://kaboomjs.com/doc#timer !!!!
