### ISSUE TITLE
how to change speed

### ISSUE THREAD

**Issue by artiely** [replit/kaboom#243]
This library is great, I am learning to use it

I specified the movement speed,

when i press `down`

Why is the speed getting faster and faster，

I want to modify the speed in `action()`, and then I found this problem

My expectation is to press down twice as fast as the original

Duplicate link

[https://replit.com/@artiely1220/SlowSimpleSubweb#code/main.js](https://replit.com/@artiely1220/SlowSimpleSubweb#code/main.js)

tks!

**Comment by slmjkdbtl** [comment]
You're registering `keyPress` inside `spawnEm()`, which runs once every second, and ends up registering a multiple key events.

This code should work as you intended? https://replit.com/@slmjkdbtl/SlowSimpleSubweb

**Comment by artiely** [comment]
I got it, thanks
