### ISSUE TITLE
Add dark mode to Kaboom docs

### ISSUE THREAD

**Issue by techpixel** [replit/kaboom#246]
It would be nice if the Kaboom docs would adjust to the system default mode (dark or light) when browsing the docs.

**Comment by techpixel** [comment]
Also I really liked this feature, why was it removed?
![image](https://user-images.githubusercontent.com/68567672/134838341-2ed12195-5179-49fc-984c-467a26160c0c.png)

**Comment by slmjkdbtl** [comment]
It's not! Just WIP. I'm just working on dark theme, I'll also add this back.

**Comment by techpixel** [comment]
Also: is there a discord support server?

**Comment by slmjkdbtl** [comment]
[Yep](https://discord.gg/aQ6RuQm3TF)

**Comment by slmjkdbtl** [comment]
Dark mode is added

**Comment by techpixel** [comment]
Thank you! Also, could you add dark mode to the landing page?
