### ISSUE TITLE
Is there a way to "place" the kaboom generated canvas within the DOM

### ISSUE THREAD

**Issue by JOKeRiino** [replit/kaboom#248]
So the game page I'm building features a "how-to" and "about" section, but as best practice says: Script tags belong at the end of the body tag. Or in other words: Even if the script tag is placed within the page, the game is always the last element loaded within the dom. Is there a way to place the canvas within (in my case - in a grid) the HTML? Give the canvas a predestined place on the page - so to speak?

**Comment by slmjkdbtl** [comment]
Yes. You can define the `root` or `canvas` attribute in `kaboom()`

- `root`: sets the parent element Kaboom will insert the canvas to
- `canvas`: the existing canvas DOM to render in
