### ISSUE TITLE
unpause function does not exist

### ISSUE THREAD

**Issue by Eric-Schumann** [replit/kaboom#25]
I can use pause() to pause the game, but unpause() doesn't exist.  Once paused, you are unable to resume.

**Comment by slmjkdbtl** [comment]
right, there's an inconsistency in the docs vs impl, in the impl its `pause(true)` and `pause(false)`, i haven't fully made up my mind on which way to go:
- `pause(true)` and `pause(false)`
- `pause()` and `unpause()`, there's also `paused()` to check the pause state, 3 similarly named functions to control a small part of the mechanism seems like a lot
- a single field `kaboom.debug.paused`? more consistent with other debug flags, just thought of this, this might be better

happy to hear yall thoughts on this interface

**Comment by slmjkdbtl** [comment]
I went for `kaboom.debug.paused` in cb5658f, lmk of any other proposal
