### ISSUE TITLE
Font not rendering some latin letters

### ISSUE THREAD

**Issue by beni69** [replit/kaboom#252]
I'm trying to render some text using `text()` and it contains some letters that are not part of the English alphabet. for example: *áéó*
Now the apl386 font says on the website that it supports all these characters and much more, however these letters just leave a space in their place in-game.
example: `aáb` becomes `a b`
I kinda like this font, so is there any way to get it to work, or if I have to use a different font, how should I go about doing that?

**Comment by slmjkdbtl** [comment]
Kaboom is using a [bitmap version of the font](https://github.com/replit/kaboom/blob/master/src/apl386o.png), which only contains ascii character. Does not have the ability to render truetype / opentype fonts yet, but planned.

**Comment by beni69** [comment]
Oh, I get it. And is there a way to make this font into a bitmap with these special characters?

**Comment by slmjkdbtl** [comment]
Yep! But I couldn't find a good tool to convert ttf to bitmap, the current one I actually just typed the ascii letters in Figma with the font and exported as png, and use image editing to tweak each letter's spacing...

**Comment by beni69** [comment]
Well, that sounds like a lot of hassle. I think I'll just use another font. If I remember correctly there is a plugin to use a font called cp437 that has support for all these things.

**Comment by slmjkdbtl** [comment]
Yeah that has a lot of characters. There's also [`CP437_CHARS`](https://kaboomjs.com/doc#CP437_CHARS) that lets you load cp437 fonts easier.

**Comment by beni69** [comment]
Great, thanks 👍
