### ISSUE TITLE
How does mouseDown() work?

### ISSUE THREAD

**Issue by JOKeRiino** [replit/kaboom#256]
I have a "button" that should increase an amount steadily as long as the button is clicked. I cannot get it to work!

**Comment by slmjkdbtl** [comment]
The callback in `mouseDown()` will run every frame as long as mouse is being held down. What is "increase" here?

**Comment by JOKeRiino** [comment]
well i have a variable "let payment = 0".
I have a GameObj "button" with area() 
Every time I click on the button, payment is increased by 100 //<- bad solution
good solution -> as long as the mouse is being held down on the button, payment should be increased by 100 in small intervals

**Comment by slmjkdbtl** [comment]
You mean like increase 100 every 0.5 second when mouse is being held down? Or increase constantly when mouse is held down

**Comment by JOKeRiino** [comment]
You mean like increase 100 every 0.5 seconds when the mouse is being held down. Yes, this one (ideally)!
(And additionally: How would the same thing work with touch?)

**Comment by slmjkdbtl** [comment]
Single touches should be automatically dealt as mouse with `mouseClick()` and `mouseDown()` etc, if not it's a bug.

So there needs to be some kind of timer then
```js
mouseClick(() => {
    const stop = loop(0.5, () => {
        money += 100;
        if (!mouseIsDown()) stop();
    });
});
```

**Comment by JOKeRiino** [comment]
This works perfectly, thank you!
