### ISSUE TITLE
Game objects on different layers do not trigger overlaps callback.

### ISSUE THREAD

**Issue by Eric-Schumann** [replit/kaboom#26]
I'm not sure if this intentional or not, but game objects on different layers will not trigger the callback defined in the overlaps function.

Example:

Player rendered on 'sprite' layer and bullet's rendered on 'bullet' layer never overlap.  Player has 'player' tag.  Bullet has 'bullet' tag.

`
overlaps('player', 'bullet', (p, b) => {
    destroy(p);
    destroy(b);
});
`

Neither are destroyed during overlap.

**Comment by slmjkdbtl** [comment]
It is a design decision for objects on different layers don't collide (looks like it's not mentioned in docs, will add)

so now layers are used for:
- control which objects are drawn on top
- have some layers not affected by the camera with `camIgnore()` (e.g. for UI)

mostly how I use it is separate background, game scene, and UI, which are kinda "different worlds", thus made the decision to not check for collision for objects on different layer (also saves a bit performance from that), but not that tied to it, let me know if you have any thoughts

**Comment by Eric-Schumann** [comment]
The issue I'm running into is when spawning a new sprite using the position of another sprite.  The new sprite appears over the top of the reference sprite.  This just becomes an issue of aesthetics.  Should bullets appear on top of the ship or from behind the ship?

**Comment by slmjkdbtl** [comment]
For draw order issue, you can also use [`readd()`](https://kaboomjs.com/#readd) to readd an object to the scene, so it'll appear in front of everyone else on that layer, does that help with your case?

**Comment by Eric-Schumann** [comment]
readd() does the trick!  Thanks.

**Comment by slmjkdbtl** [comment]
Good to hear!
