### ISSUE TITLE
Overlaps function no longer defined in Kaboom update

### ISSUE THREAD

**Issue by rideam** [replit/kaboom#274]
We were using the `overlaps` function for this [Snake game tutorial](https://docs.replit.com/tutorials/21-build-snake-with-kaboom) to ensure the game does not end by the snake merely brushing against the boundary wall for example as is the case with the closest alternative function [collides](https://kaboomjs.com/doc#collides) but the `overlaps` function is no longer defined in the new version of Kaboom.

```javascript
overlaps("snake", "wall", (s, w) => {
    run_loop = false;
    camShake(12);
    respawn_all();
});
```

Trying to use `collides` in the same context produces this error:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/31291528/136966802-da2b2ba6-4cf3-47da-9efc-7a8aaa6618ef.png">

**Comment by slmjkdbtl** [comment]
Hi! You'll have to give it an `area()` component (used to be automatically generated by components like `sprite()` and `rect()`)
```js
add([
    rect(20, 20),
    area(), // this will generate the collider and give you methods like `collides`
]);
```
with settings:
```js
add([
    rect(20, 20),
    origin("center"),
    area({ scale: 0.5 }), // the collider is half the visual size
]);
```

for more check out `area()` in the [doc](https://kaboomjs.com/#area)

**Comment by rideam** [comment]
okay thanks
