### ISSUE TITLE
area() collider with rotate

### ISSUE THREAD

**Issue by codergautam** [replit/kaboom#276]
So I know that rotate doesn't work with the area collider. I have a image of a sword and I am rotating it. I need to check for collisions with the sword and other game objects. Is there any other method of doing this (without using area collider). I need it badly for my game.

**Comment by codergautam** [comment]
This is what I'm trying to achieve-

https://user-images.githubusercontent.com/66850133/138370994-d3149e59-834f-46e2-9eb1-3069f568e7b1.mp4

**Comment by dbarnett** [comment]
In the meantime, could there be a link from the docs for `area()` to the context on what doesn't work? It's off-putting to just see it "doesn't work" and not have any idea what will happen if you happen to need rotate and collide on the same object.

For instance, will the current behavior get close enough to what you'd want in some cases? It looks like Inspect mode will show you whatever collision area it's currently using, and https://github.com/replit/kaboom/issues/157#issuecomment-907729629 has some ideas for better collision detection?

**Comment by codergautam** [comment]
I ended up using a custom collision function that basically gets a bunch of lines from the sword base to the sword tip, and checking them against the other enemies.
