### ISSUE TITLE
Resize the rendered sprite alone

### ISSUE THREAD

**Issue by sanvishal** [replit/kaboom#293]
Is there a way to resize/scale the sprite alone without scaling the area() collider?

When I try to dynamically set `player.width = 16` inside update(), it doesn't resize the sprite (it actually does nothing) but it modified the width field in the game object.

Weird thing is that,
when I use `rect()` instead of `sprite()`, the `player.width = 16` actually works!

**Comment by lajbel** [comment]
you can use https://kaboomjs.com/#scale and a specific area size...

**Comment by sanvishal** [comment]
yes, scale() also resizes the area() collider, when I again resize the area() collider with the original size, it messes up the collisions, and sometimes the object clips through other solid()s
