### ISSUE TITLE
'destroy' method broken : Uncaught TypeError: obj.exists is not a function

### ISSUE THREAD

**Issue by matthewlawrenceklein** [replit/kaboom#3]
`destroy()` method does not work correctly, returning the error referenced below. Conversely, `destroyAll()` functions as anticipated in the same scenarios. Full error messaging below:

        Uncaught TypeError: obj.exists is not a function
            at destroy (kaboom.js:2191)
            at Object.cb (main.js:59)
            at frame (kaboom.js:2403)

**Comment by slmjkdbtl** [comment]
Hi! Thanks for the report! Can you provide a minimal reproducible example? It seems to work on all the examples, are you passing a valid game object?

**Comment by matthewlawrenceklein** [comment]
thanks for the quick response! It's very possible I'm doing something incorrectly :) Here's a quick example, feel free to sub in any sprite asset 

                kaboom.global();
        loadSprite('guy', '../assets/badboy.png')
        
        init({
            fullscreen : true, 
            scale : 2
        });
        
        
        scene('main', () => {
            let guy = [
                sprite('guy'),
                'guy',
                scale(3)
            ]
            add(guy)
        
            keyPress('a', () => {
                destroy(guy)  // produces the aformentioned error 
            })
        
            keyPress('b', () => {
                destroyAll('guy') // destroys the guy 
            })
            
        })
        
        start('main')

**Comment by slmjkdbtl** [comment]
oh i see, so you have to pass in the reference returned by `add()` to `destroy()`, `add()` takes in a component list and returns the actual game object reference, and the list it receives stays a plain list, so

```js
const guy = add([
    sprite('guy'),
    'guy',
    scale(3)
]);

// somewhere
destroy(guy);
```

**Comment by matthewlawrenceklein** [comment]
gotcha, thanks! Extending the same example

         kaboom.global();
        loadSprite('guy', '../assets/badboy.png')
        
        init({
            fullscreen : true, 
            scale : 2
        });
        
        
        scene('main', () => {
            let guy = add([
                sprite('guy'),
                'guy',
                scale(3)
            ])
            
        
            keyPress('a', () => {
                destroy(guy) 
            })
        
            keyPress('b', () => {
                destroyAll('guy')
            })
        
            keyPress('c', () => {
                add(guy)
            })
            
        })
        
        start('main')

I'm now able to `destroy` guy, then `add` guy, but am not able to destroy the subsequent `guy`. Trying to figure out the best way to recycle object code without redeclaring each time. Thanks for your help!

**Comment by slmjkdbtl** [comment]
I would make an `addGuy()` function

if you want to keep adding, and destroying the latest guy, try this
```js
function addGuy() {
    return add([
        sprite("guy"),
        scale(3),
        "guy",
    ]);
}

let guy = addGuy();

keyPress("a", () => {
    destroy(guy);
});

keyPress("c", () => {
    // keep "guy" referencing the newest guy
    guy = addGuy();
});

```

**Comment by matthewlawrenceklein** [comment]
@slmjkdbtl super helpful, thanks! And congrats on the librart release!

**Comment by slmjkdbtl** [comment]
Thank you 😋
