### ISSUE TITLE
Playing Aseprite animation fix

### ISSUE THREAD

**Issue by warang580** [replit/kaboom#32]
I've tried using an aseprite animation but can't get it to work. I've finally found the problem, and after changing

```js
play(name, loop) {
	const anim = spr[this.spriteID].anims[name];
```
to
```js
play(name, loop) {
	const anim = assets.sprites[this.spriteID].anims[name];
```

it worked.

I'm not sure if it's related to aseprite plugin, or related to core. I can make PR if needed

**Comment by slmjkdbtl** [comment]
Nice catch, thanks! Fixed in bba3d1d and I just released v0.4.1 that includes this fix
