### ISSUE TITLE
The kaboom website is using ~70% CPU for no reason

### ISSUE THREAD

**Issue by vanlong441** [replit/kaboom#322]
Just open up the task manager and see it for yourself.
Website: https://kaboomjs.com/

**Comment by slmjkdbtl** [comment]
I wonder if it's the scrolling background (which no one can actually see lol)

<img width="1144" alt="1634779605" src="https://user-images.githubusercontent.com/9929523/138195487-fe01fcce-dab1-4b9b-98d7-ced98cbc254d.png">

Can you try if it goes normal if you cross off these animation css here? (select the div that's 2 levels down `"#__next"`)

**Comment by slmjkdbtl** [comment]
I think it should be good now, please reopen if it's still a problem
