### ISSUE TITLE
addLevel does not pass location vector to function

### ISSUE THREAD

**Issue by techpixel** [replit/kaboom#336]
```js
			const p = vec2(...args);

			const comps = (() => {
				if (opt[sym]) {
					if (typeof opt[sym] !== "function") {
						throw new Error("level symbol def must be a function returning a component list");
					}
					return opt[sym](p);
				} else if (opt.any) {
					return opt.any(sym, p);
				}
			})();
```

`p` should pass to `opt[sym]` in the spawn function, but it doesn't seem to work. 

I *believe* this is a bug, but I'm not sure why it's happening. I used the `addLevel` and `grid` functions directly into my code (copy/paste), and it works.

Hopefully this can be fixed soon, since it's beneficial in locating level tiles by their position.

**Comment by slmjkdbtl** [comment]
Closing this for now, please reopen if this is still an issue

**Comment by techpixel** [comment]
Sorry for the late reply.

https://replit.com/@HarperframeInc/hugo-iss-rep#code/main.js

**Comment by slmjkdbtl** [comment]
Looks like you're on the beta version, if you `npm install kaboom@latest` you should get that

**Comment by techpixel** [comment]
Okay, thank you.
