### ISSUE TITLE
hovers callback doesn't work unless mouse is down

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#375]
Steps to reproduce:
Go to current button demo:
https://kaboomjs.com/play?demo=button

Hover over the buttons 

Nothing happens.

Hold the left button down and then hover over buttons 
They respond like you would expect without having the left mouse button down.

hovers() should not depend on having the mouse button down.

**Comment by triptych** [comment]
Note, it doesn't matter which button ( right, left middle) you hold down - hover "works" if any of them are down, but NOT when you aren't holding a mouse button down.

**Comment by slmjkdbtl** [comment]
What browser & machine you're on? Can't repro on my Macbook with Chrome / FF / Safari

**Comment by slmjkdbtl** [comment]
Curious if you're picking up mouse move events at all. Does `mousePos()` give you the latest mouse position?

**Comment by triptych** [comment]
Version 95.0.4638.69 (Official Build) (64-bit) Windows 
Device name	DESKTOP-ACN1IPP
Processor	Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   1.80 GHz
Installed RAM	8.00 GB (7.83 GB usable)
Device ID	D2C430AF-398B-4796-8FF7-BDAFBD508D6C
Product ID	00325-81370-62044-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

**Comment by triptych** [comment]
Edition	Windows 10 Home
Version	21H1
Installed on	‎7/‎5/‎2020
OS build	19043.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by triptych** [comment]
I tested on my own MacBook Pro and hover works there as expected. Weird.

**Comment by triptych** [comment]
Tested on Microsoft Edge on my PC and it also doesn't work.
Microsoft Edge
Version 95.0.1020.38 (Official build) (64-bit)

**Comment by slmjkdbtl** [comment]
So it doesn't work on Windows on any browser? Does mousePos work there?

**Comment by triptych** [comment]
That example DOES work - the sprites follow the mouse and animate.

**Comment by slmjkdbtl** [comment]
I think it's because your windows device might support touch, and it checks for mouseDown for hover event if it's on touch device [here](https://github.com/replit/kaboom/blob/c3fea04f49edeb56024f48a3b0d254a3cfc7792e/src/kaboom.ts#L1390-L1391). 

The `isTouch` is checked [here](https://github.com/replit/kaboom/blob/c3fea04f49edeb56024f48a3b0d254a3cfc7792e/src/app.ts#L205) As a workaround before the fix, can you try if 
```
window. ontouchstart = null;
navigator.maxTouchPoints = 0;
```
before `kaboom()` fixes this case?

**Comment by triptych** [comment]
I'm testing on another windows desktop and hover does work. 
I tested on my laptop with Firefox and it doesn't work. 

Sorry this is frustrating for me as well.

**Comment by triptych** [comment]
I will try that in the demo

**Comment by triptych** [comment]
I ran this:
``` // simple UI
window.ontouchstart = null;
navigator.maxTouchPoints = 0;
kaboom();

function addButton(txt, p, f) {

	const btn = add([
		text(txt, 8),
		pos(p),
		area({ cursor: "pointer", }),
		scale(1),
		origin("center"),
	]);

	btn.clicks(f);

	btn.hovers(() => {
		const t = time() * 10;
		btn.color = rgb(
			wave(0, 255, t),
			wave(0, 255, t + 2),
			wave(0, 255, t + 4),
		);
		btn.scale = vec2(1.2);
	}, () => {
		btn.scale = vec2(1);
		btn.color = rgb();
	});

}

addButton("Start", vec2(200, 100), () => debug.log("oh hi"));
addButton("Quit", vec2(200, 200), () => debug.log("bye"));

// reset cursor to default at frame start for easier cursor management
action(() => cursor("default"));
``` 

in the demo viewer. No difference. ( No hover ) 

It seems this is a pretty obscure issue -  wouldn't blame you if you set this as low priority.

**Comment by triptych** [comment]
Yes, I'm using an all in one laptop with a touch screen.

**Comment by slmjkdbtl** [comment]
There's a chance the browser won't let you change `navigator.maxTouchPoints` so kaboom still thinks it's a touch device, but this should be fixable on next release maybe we just don't special case touch devices here.

**Comment by triptych** [comment]
Ok if you get a build you'd like me to test I'd be happy to test the fix on this laptop.

**Comment by triptych** [comment]
Yeah MDN says it's read only :
``` The maxTouchPoints read-only property of the Navigator interface returns the maximum number of simultaneous touch contact points are supported by the current device. ```
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints

**Comment by triptych** [comment]
In my console:
``` navigator.maxTouchPoints
10```

**Comment by slmjkdbtl** [comment]
That's a lot of touch points
