### ISSUE TITLE
documentation request: how to update properties

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#379]
most of the documentation covers **initialization** of various properties like color() - but it does not show how to update them via code.  Currently, the only way for someone to learn how is to look at the examples and trial and error.

Request: include examples for each component - how to update it after it's been initialized

color --> how to update color?
text --> how to update value and change font or size?
outline --> how to add an outline on say hover over an element?
z --> how to change the z dynamically?

If there is some generic knowledge for updating "anything" please document that.

**Comment by slmjkdbtl** [comment]
Yeah this is better explained in the docs on master which will be released next week with the new version.

A kinda hidden thing right now is you're supposed to check the return type to see what it offers, e.g. for the `text()` component you'll click the returned `TextComp` type 

<img width="369" alt="1635714448" src="https://user-images.githubusercontent.com/9929523/139601277-647aabc2-a361-4230-b92d-346927fc57d3.png">

where all fields on this component will be directly assigned to the game object, and you just operate on these fields normally.
