### ISSUE TITLE
drive.js example is broken

### ISSUE THREAD

**Issue by TKTheTechie** [replit/kaboom#38]
It appears that the drive.js example is broken ..

https://github.com/replit/kaboom/blob/master/examples/drive.js

On line 10, Seems that the function loadAseprite no longer exists?

**Comment by slmjkdbtl** [comment]
oops nice catch, fixed in 6965f9c (introduced a plugin system in v0.4.0 and made asperite spritesheet loading a plugin that needs manual import)
