### ISSUE TITLE
documentation request: how to make custom components

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#380]
In the concert demo code you introduce a custom component : 
``` 
function bounce() {
	let bouncing = false;
	let timer = 0;
	return {
		id: "bounce",
		require: [ "scale" ],
		update() {
			if (bouncing) {
				timer += dt() * 20;
				const w = Math.sin(timer) * 0.1;
				if (w < 0) {
					bouncing = false;
					timer = 0;
				} else {
					this.scale = vec2(1 + w);
				}
			}
		},
		bounce() {
			bouncing = true;
		},
	};
}
```

Which appears to have a kind of API with things like require, and update() and add() 
This is also in other demo examples like the drag example .

Creating these custom off the cuff components seems to be a core feature of Kaboom, yet the way to make them and how they work is not documented anywhere. 

Can you please  walk through all the options for creating a custom component? 
what is the minimum object to return? 
what does update() do ?
what does add() do in a custom component? 
what other lifecycle methods are there? destroy?

I'm sure these could be "guessed" at, but this seems like a core functionality that's not documented.

**Comment by slmjkdbtl** [comment]
These are documented [here](https://github.com/replit/kaboom/blob/master/doc/comp.md) and will be in a demo [here](https://github.com/replit/kaboom/blob/tw-more-demo/demo/comp.js), and will be surfaced properly on the website next week!

**Comment by triptych** [comment]
Awesome! I'm glad I'm building a simple game where I'm coming across the need for all of this. The more I use Kaboom the more I like it.

**Comment by triptych** [comment]
This is so funny! I just stumbled across the need for this, and you already have it all spelled out plus you referenced the demos I found the components in ... guess I will go over the source more thoroughly before filing bugs !

**Comment by slmjkdbtl** [comment]
No prob! I know the doc is still a bit rough these days, but it'll get better every week.

**Comment by slmjkdbtl** [comment]
There's also a tutorial in [this demo](https://kaboomjs.com/play?demo=component)
