### ISSUE TITLE
loadShader not working

### ISSUE THREAD

**Issue by yikuansun** [replit/kaboom#382]
I'm having trouble with shaders in Kaboom... here is a picture of my problem:
![image](https://user-images.githubusercontent.com/38194363/139877060-7fc57b7f-b485-483d-802a-69a2b0c04dcd.png)
Note that I have checked that `shaders/glow.glsl` does exist.
Here is the Replit workspace: https://replit.com/@YikuanSun/GameOffSubmission#code/main.js

Additionally, I tried the sample shader code in the documentation and got errors:
![image](https://user-images.githubusercontent.com/38194363/139877392-7ecbb3d1-7f88-45da-8155-99c8d64a86f6.png)
![image](https://user-images.githubusercontent.com/38194363/139877545-9c95cb95-12b3-49b6-9e59-624c495fcae5.png)

**Comment by slmjkdbtl** [comment]
The last argument is 'isUrl', it should be false in your case

**Comment by yikuansun** [comment]
@slmjkdbtl Thanks for the reply! For my first picture, I was trying to use a URL, specifically, `shaders/glow.glsl`. Am I doing it incorrectly?

The second picture was straight out of Kaboom docs.

**Comment by slmjkdbtl** [comment]
Ooh, I see. The Kaboom template only staticly serve these folders in `run.js`
```js
app.use("/sprites", express.static("sprites"));
app.use("/sounds", express.static("sounds"));
app.use("/code", express.static("code"));
app.use("/dist", express.static("dist"));
```

It'll work if you add a 
```js
app.use("/shaders", express.static("shaders"));
// or just serve everything
app.use(express.static(__dirname));
```

here. (It's updated in the template to serve everything)

Also you'll need to adjust the shader to fit the Kaboom custom shader format

**Comment by yikuansun** [comment]
Got it. Thank you!
