### ISSUE TITLE
The examples of the levels don't start on left side

### ISSUE THREAD

**Issue by ptkdev** [replit/kaboom#401]
<img width="1049" alt="Schermata 2021-11-08 alle 19 37 06" src="https://user-images.githubusercontent.com/442844/140798801-613007b4-6eb6-40da-b363-87b54df33d05.png">

**Comment by oaklandgit** [comment]
I believe this is because the example has the camera following the character.

I do think that the camPos() function should have parameters for setting limits. Maybe a feature request.

**Comment by ptkdev** [comment]
Yes, but is hard with camPos() move "screen" when player is on border. If CamPos follow player create big empty space and set player on center (ugly - but correct), but set player on left don't move screen easy if player go to right and get the right side.

**Comment by slmjkdbtl** [comment]
I think this is left for the game to implement, kaboom won't know what'll be the "border" for your specific game.

**Comment by Zachiah** [comment]
I used code like this on my game
```
player.action(() => {
  k.camPos({
    x: Math.max(k.width() / 2, player.pos.x),
    y: Math.min(k.height() / 2, player.pos.y),
  });
});
```

**Comment by ptkdev** [comment]
@Zachiah if you sum() width of sprite this work perfectly!
<img width="1644" alt="Schermata 2021-11-17 alle 12 10 25" src="https://user-images.githubusercontent.com/442844/142189800-8e885085-7d8b-422b-9535-b8163e7e0103.png">

**Comment by Zachiah** [comment]
Just so you know it's the screen with but yeah
