### ISSUE TITLE
width and height trouble when letterbox is true . I'm not sure if it's a bug or not.

### ISSUE THREAD

**Issue by micheg** [replit/kaboom#407]
The methods width() and height() always report the height and width of the canvas even if we use a configuration object when initializing the library.

For example the documentation reports for the kaboom method, the use of the KaboomOpt object which has the properties:

    width?: number Width of game.
    height?: number Height of game.

And always the documentation:

    width() => number
    Get the width of game.
    height() => number
    Get the height of game.

So I expect the following code:

      kaboom(
      {
        width: 480,
        height: 800,
        global: true,
        stretch: true,
        letterbox: true
      });
      console.log(`width is => ${width()}`);
      console.log(`height is => ${height()}`);

prints:

    width is => 480
    height is => 800

Instead I get: (ex)

    width is => 2694
    height is => 800

which is the resolution of the canvas (and actually not even correct) and not that of the "game", this leaves me a bit perplexed and forces me not to be able to use width() and height().
And it is not possible to use the center() method either because it is defined as follows:

    function center(): Vec2 {
        return vec2(width() / 2, height() / 2);
    }

And in my case it comes back: x: 1348., y: 400 instead of x: 200, y: 400.
and therefore probably other methods as well ...

I think the problem lies here:

    if (gopt.letterbox) {
        // TODO: not working
        const r1 = gl.drawingBufferWidth / gl.drawingBufferHeight;
        const r2 = gopt.width / gopt.height;
        if (r1 > r2) {
            gfx.width = gopt.height * r1;
            gfx.height = gopt.height;
            const sw = gl.drawingBufferHeight * r2;
            const sh = gl.drawingBufferHeight;
            const x = (gl.drawingBufferWidth - sw) / 2;
            gl.scissor(x, 0, sw, sh);
            gl.viewport(x, 0, gl.drawingBufferWidth, gl.drawingBufferHeight);
        } else {
            gfx.width = gopt.width;
            gfx.height = gopt.width / r1;
            const sw = gl.drawingBufferWidth;
            const sh = gl.drawingBufferWidth / r2;
            const y = (gl.drawingBufferHeight - sh) / 2;
            gl.scissor(0, gl.drawingBufferHeight - sh - y, sw, sh);
            gl.viewport(0, -y, gl.drawingBufferWidth, gl.drawingBufferHeight);
        }

I'm not sure about the calculations done to put the sidebars, but I believe that system that updates gfx.height and gfx.width and then returns them in the relative methods:

	// get game width
	function width(): number {
		return gfx.width;
	}

	// get game height
	function height(): number {
		return gfx.height;
	}

is not correct, I believe that the methods should always return the one passed in the constructor of kaboom, i.e. gopt.width and gopt.height.

After taking a look at gfx.ts I think the main problem is that the width and height methods are used both internally by the library and exposed to the user.
And everything works fine if there are no virtual viewports, as in the case of basic fullscreen and or stretching but becomes problematic in the case of letterboxes.

**Comment by slmjkdbtl** [comment]
Letterbox is currently bugged as written in the comment, will be revisited soon!

**Comment by micheg** [comment]
But it's not just a question of the letterbox, even the stretch doesn't work very well, I have elements that are not clickable with the active stretch, I'll try to make an example with some code.

**Comment by slmjkdbtl** [comment]
Should be fixed in #490, plz reopen of problem persists.
