### ISSUE TITLE
Can you export kaboom in the npm library?

### ISSUE THREAD

**Issue by TKTheTechie** [replit/kaboom#41]
Hi,

I'm trying to import kaboomjs in a node project but I see that the kaboom object is not exported. Can that be done?

Thanks.

**Comment by slmjkdbtl** [comment]
Soon kaboom will use esbuild to generate files for each module system!

**Comment by TKTheTechie** [comment]
Awesome thanks - I think I figured out how to import and use the kaboom module mostly. However, its not clear to my how to load the asepritePlugin from within my kaboom app. Can you provide some guidance?

**Comment by slmjkdbtl** [comment]
for sure i'll look into it in a bit, right now kaboom is using the `package.json` fields
```json
"exports": {
	"import": "./dist/kaboom.mjs",
	"require": "./dist/kaboom.cjs"
}
```
to handle importing the base library, not sure if you can do similar for multiple files in a single npm package, I'm not a front-end lib releasing expert and have to do a bit research on this (If anyone comes across and happens to know a good way to do this please let me know, appreciated!)

**Comment by slmjkdbtl** [comment]
Solved by f8ceecf and ed1627d, now you can
```js
import asepritePlugin from "kaboom/plugins/aseprite";
```

(TODO: TypeScript type defs for the plugins)

**Comment by TKTheTechie** [comment]
Nice it works! Can you push it to npm?

**Comment by slmjkdbtl** [comment]
sure i'll release a `v0.5.1` soon to include this

**Comment by slmjkdbtl** [comment]
Done 👌 . Looks like this is resolved, closing this again.

**Comment by triptych** [comment]
Can you please add this somehow to the docs for other folks?
