### ISSUE TITLE
Is there a way to react to a cleanup() event? And if not, should there be one? 

### ISSUE THREAD

**Issue by JOKeRiino** [replit/kaboom#416]
I am creating game objects, with the cleanup() param, but every time one of those objects gets destroyed, I'd like to spawn a new one.

Is there an onCleanup() event listener yet?
And if not directly, is there a way to react to it,
other than not using the cleanup and destroying the items manually? 

Maybe a better way to integrate this would be to add an arrow function to the cleanup() and do whatever should happen after the cleanup like this: cleanup(3, () => {})? - just an idea.

**Comment by lajbel** [comment]
u can use the "out" event

```js
const obj = add([...]);

obj.on("out", () => {
    console.log("out!");
});
``` 

For more info see [this demo](https://kaboomjs.com/play?demo=out)

**Comment by JOKeRiino** [comment]
While this kind of works, it's not ideal because I'm spawning the objects out of screen, too and therefore the event gets triggered right at the spawn of the objs! I guess I'll just do it manually and not use the cleanup method.

**Comment by slmjkdbtl** [comment]
You can use `onDestroy()`
