### ISSUE TITLE
Mobile browser freezes upon too many kabooms

### ISSUE THREAD

**Issue by jwsy** [replit/kaboom#417]
This freezes on a mobile browser and occasionally on a laptop. Reproduce by waiting a second for a three "fires" to appear nearby and tap on them to have the avocado put them out and grow. The mobile browser freezes. I've changed this app to spawn a lot more fires on line 318

Kaboom v2000.1.3
Site hosted by replit: https://avocado-remix-mobile-browser-freeze-too-many-kabooms.jwsy.repl.co
Source: https://replit.com/@jwsy/avocado-remix-mobile-browser-freeze-too-many-kabooms

![kaboom freeze MP4](https://user-images.githubusercontent.com/446031/141711894-01871b4b-6c56-4817-8b9c-b086c2ae41d4.gif)

**Comment by slmjkdbtl** [comment]
Does the console log anything when freeze? 

Does [this demo](https://kaboomjs.com/play?demo=kaboom) freeze on your device

**Comment by jwsy** [comment]
That demo does not freeze on my mobile device (iPhone on Safari) 👍 . Apologies about not having any logs and being able to run that demo perfectly definitely implies dev error 😅 

For future reference just in case others see this, I've made these two replits with only one line of difference, and only the first one without the kabooms (that my toddler loves) crashes. I've pasted a gist of the code below 
1. https://replit.com/@jwsy/avocado-remix-mobile-browser-freeze-too-many-kabooms#code/main.js
2. https://replit.com/@jwsy/avocado-remix-mobile-browser-NO-kabooms#code/main.js

``` Javascript
collides("avocado", "enemy", (b, e) => {
  // console.log(JSON.stringify(e) );
  destroy(e);
  //addKaboom(e.pos); //*** this is the only difference between the two 
  if (e.is("rainbowpoop")) {
    score.value += 10;
    shake(12);
  }
  else {
    score.value += 1;
    shake(b.dScale * 3);
  }
  if (b.dScale < 12) {
    b.dScale = b.dScale + 0.5;
  }
  else {
    go("end");
  }
  b.isOFaced = true;
  b.lastOFaceTime = time();
  score.text = score.value;
  play('o');
});
```

**Comment by jwsy** [comment]
This is fixed in the latest version of Kaboom, closing

Updated version uses the updated API, I assume that was the issue: https://replit.com/@jwsy/avocado-remix
