### ISSUE TITLE
Additional arguments onStateEnter are undefined

### ISSUE THREAD

**Issue by WebdevAlexTV** [replit/kaboom#424]
### Version

v2000.1.4

### What browsers are you seeing the problem on?

Chrome, Firefox

### What happened?

The additional parameter is undefined. The console output is:

```
SHOVEL INTO undefined
```

### What's the expected behavior?

The console output should be:

```
SHOVEL INTO right
```

### Minimum reproducable code

```
const player = k.add([
    k.pos(16, constants.tileSize / 2),
    k.sprite("player", { frame: 0 }),
    k.state("idle", ["idle", "shovel"]),
    "player",
  ]);

  player.onStateEnter("shovel", (direction) => {
    console.log("SHOVEL INTO", direction);
  });

/** ... */

player.enterState("shovel", "right");
```

### Is there an existing issue for this?

- [X] I've searched and there is no existing issue for this bug

**Comment by slmjkdbtl** [comment]
This is embarrassing hh keeping having problems with this. Fixed in #425 and released as v2000.1.5
