### ISSUE TITLE
Add example with animation

### ISSUE THREAD

**Issue by ipante** [replit/kaboom#43]
Hi there,

I'm trying to add an animation (manually created from a spritesheet) to a character, but I can't get it working. If I'm right, the only example using this feature is "drive", which extracts data from a json file. Another straightforward example (manually split, add animation and play) would be really useful !

PS : many thanks for Kaboom.js ! I can't wait to see Kaboom grow and I'm really impatient to use it with my students :)

**Comment by slmjkdbtl** [comment]
Sure! I just updated the [drive example](https://kaboomjs.com/examples#drive) to use manual slice and anim definition.

And sorry I realized the doc isn't updated, there's changes to the interface so now it's using `from` and `to` instead of an array. It's updated on the website now.
```
loadSprite("car", "img/car.png", {
	sliceX: 3,
	anims: {
		move: {
			from: 0,
			to: 1,
		},
		idle: {
			from: 2,
			to: 2,
		},
	},
});
```

**Comment by ipante** [comment]
That's perfect, thank you very much !
