### ISSUE TITLE
Without Hardware Acceleration -> FPS too low

### ISSUE THREAD

**Issue by Chandra-Panta-Chhetri** [replit/kaboom#434]
### Version

v2000.1

### What browsers are you seeing the problem on?

Chrome, Other

### What happened?

Without hardware acceleration, I am getting around 9-14 FPS which makes the game extremely laggy. When hardware acceleration is on, I get around 60 FPS which is good. The game is a super simple one - a character that moves left, right or jumps.

### What's the expected behavior?

FPS should be higher or game should not appear too laggy when hardware acceleration is off.

### Is there an existing issue for this?

- [X] I've searched and there is no existing issue for this bug

**Comment by slmjkdbtl** [comment]
What code are you running? Kaboom does only use WebGL for rendering which is supposed to be run on GPU, performance diff is expected

**Comment by lajbel** [comment]
Closed due to no response
