### ISSUE TITLE
`origin` comp making GameObj type inference not working

### ISSUE THREAD

**Issue by slmjkdbtl** [replit/kaboom#451]
### Version

v2000.1

### What happened?

`window.origin` exists in browser and ts default definitions, which confuses ts with kaboom's own `origin(): OriginComp`, making game object type inference not working

### What's the expected behavior?

`window.origin` should give kaboom's definition

### Minimum reproducable code

```ts
// this will be a GameObj<any> instead of a GameObj<PosComp | RectComp | OriginComp>
const thing = add([
    pos(120),
    rect(80, 40),
    origin("center"),
])
```

### Is there an existing issue for this?

- [X] I've searched and there is no existing issue for this bug

**Comment by DaInfLoop** [comment]
Cannot reproduce

Info:
Chrome 84.0.4147.125
OS: Ubuntu 18.04.3 LTS

![Cannot reproduce on Chrome](https://cdn.discordapp.com/attachments/900072198851657808/920372256490803240/unknown.png)

however....

Can reproduce

Info:
Visual Studio Code 1.63.0
OS: Ubuntu 18.04.3 LTS

(VSC removed the type popup when I screenshotted, so here's the typing)

![Can reproduce on Visual Studio Code](https://cdn.discordapp.com/attachments/900072198851657808/920373120420962384/unknown.png)

**Comment by lajbel** [comment]
**Recomendations:**

Rename to originpoint()
Rename to opoint()
Add a propety in all drawble things for use the origin, in TextCompOpt, SpriteCompOpt or RectCompOpt (this reminds me of `noArea: boolean` xD)
In pos Comp add a option for set the origins

**Comment by slmjkdbtl** [comment]
`origin` as a property in drawable options actually makes a lot of sense, since it's completely tied to the drawables. I'll keep looking for ways to make it work with typescript, if no luck maybe have to resolve into one of these breaking changes

**Comment by DaInfLoop** [comment]
Another issue similar to this: `KaboomCtx#focus` and `HTMLElement#focus`, making it when you build Kaboom with typescript, you can't do it.

![Errors when building Kaboom with typescript](https://media.discordapp.net/attachments/883782079802908772/930985712294191154/unknown.png)

**Comment by slmjkdbtl** [comment]
I think changing the name and avoiding conflict is probably the best way to go.

Candidates for `origin` replacement:
- `pivot`
- `offset`
- `anchor`

Not sure about good replacement for `focus()`, maybe we just remove these since it's just calling
```js
canvas.focus()
```
and it's trivial to write by hand

**Comment by slmjkdbtl** [comment]
I think changing the name and avoiding conflict is probably the best way to go.

Some candidates for `origin` replacement:

- `pivot`
- `offset`
- `anchor`

**Comment by lajbel** [comment]
korigin (kaboom origin)
oorigin (object origin) 
originn (origin no-conflict)

**Comment by slmjkdbtl** [comment]
These have a chance of causing more confusion I think 🤔 if we're proceeding with a breaking change might as well make it a normal word

**Comment by DaInfLoop** [comment]
+1

**Comment by lajbel** [comment]
> These have a chance of causing more confusion I think 🤔 if we're proceeding with a breaking change might as well make it a normal word

Oh I was only joking hh

**Comment by slmjkdbtl** [comment]
hh sry 😆
