### ISSUE TITLE
Fire onTouchEnd on canvas touchend event not on touchmove

### ISSUE THREAD

**Issue by thomashermant** [replit/kaboom#452]
### Version

v2000.1

### What browsers are you seeing the problem on?

Other

### What happened?

The event **onTouchEnd** is triggered on the canvas **touchmove** not on **touchend**.

```
app.canvas.addEventListener("touchmove", (e) => {
	[...e.changedTouches].forEach((t) => {
		game.trigger("onTouchEnd", t.identifier, vec2(t.clientX, t.clientY).scale(1 / app.scale));
	});
});
```

need to be 

```
app.canvas.addEventListener("touchend", (e) => {
	[...e.changedTouches].forEach((t) => {
		game.trigger("onTouchEnd", t.identifier, vec2(t.clientX, t.clientY).scale(1 / app.scale));
	});
});
```

### What's the expected behavior?

I expect to fire the right event on the right event 😉 

### Minimum reproducable code

import kaboom from 'kaboom'

kaboom();

onTouchEnd((id, endPos) => {
  console.log('onTouchEnd');
}

### Is there an existing issue for this?

- [X] I've searched and there is no existing issue for this bug

**Comment by slmjkdbtl** [comment]
Thank you, fixed by #456.

Feel free to submit a PR if you got the solution!
