### ISSUE TITLE
Bug in flappy bird guide

### ISSUE THREAD

**Issue by luizbills** [replit/kaboom#47]
Sometimes in https://kaboomjs.com/guide#8 the sprite falls and don't collides with the platform.

**Comment by luizbills** [comment]
In https://kaboomjs.com/guide#9 is more easy to replicate. Just hit space several times and the high fall speed will make the sprite pass through the platform.

**Comment by slmjkdbtl** [comment]
Weird. Looks like you're getting very big `dt()` causing the bird to move directly pass the platform instead of colliding with it at any frame. Is this example also laggy when the collision doesn't work?

**Comment by luizbills** [comment]
Average fps is always 45~50 here.

I found that post https://gafferongames.com/post/fix_your_timestep/ ... maybe can be a solution

**Comment by slmjkdbtl** [comment]
What browser are you on? That example shouldn't be lagging any frame rate 🤔

**Comment by luizbills** [comment]
> What browser are you on? 

Firefox (~50 fps) and Chrome (60 fps). In chrome also occurs but less frequently.
