### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by sebringj** [replit/kaboom#5]
I saw this on Hacker News, is great!

I'm having to guess a lot of stuff for now but it's early days. I found out changing direction...
```
obj.use(scale(-1, 1)) // going from right to left movement
```
but could use some more explicit examples OR more method but it's early days all good.

thx!

**Comment by slmjkdbtl** [comment]
Thanks for the suggestion! Yeah the examples are not really complete yet, will add this one!

**Comment by slmjkdbtl** [comment]
`SpriteComp#flipX` is demonstrated in [this demo](https://kaboomjs.com/play?demo=sprite)
