### ISSUE TITLE
Game guide get's stuck on step 18

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#50]
The flappy bird game guide stops on the point where it suggests to make a score:

![image](https://user-images.githubusercontent.com/8691/119269461-aca20380-bbac-11eb-9e1e-1028261f6d4d.png)

Steps to repeat:
1) go to https://kaboomjs.com/guide in chrome on windows
2) hit next till you see this panel above -- it's at https://kaboomjs.com/guide#18
3) observe the tutorial stops advancing.

**Comment by slmjkdbtl** [comment]
Yep the score section is incomplete, will complete shortly!

**Comment by triptych** [comment]
Oh! I see. Maybe put a "more coming soon" or something - to give the folks going through the tutorial some clue that more is coming.

**Comment by jonathanphz** [comment]
I came here because of this too :)

**Comment by slmjkdbtl** [comment]
completed the guide in b55f216, sorry for the late!
