### ISSUE TITLE
Kaboom examples - button  example text broken

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#51]
Steps to reproduce:
got to https://kaboomjs.com/examples#button 
View the rendered result- >  
<img width="375" alt="Screen Shot 2021-05-24 at 4 45 00 PM" src="https://user-images.githubusercontent.com/8691/119419586-70a39700-bcaf-11eb-87af-1bd9c3ad9e15.png">

Expect to see:  Text on the Buttons.
Actually see:  Text is obscured by black rectangles.

If you comment out the `rect()` call, the text reappears:
```
add([
			text(txt),
			pos(p),
			//rect(100, 100),
			origin("center"),
			color(0, 0, 0),
		]);
```
<img width="281" alt="Screen Shot 2021-05-24 at 4 47 41 PM" src="https://user-images.githubusercontent.com/8691/119419747-c8420280-bcaf-11eb-98c5-40474cc467bb.png">

Is this intentional or a bug?

**Comment by slmjkdbtl** [comment]
Yes this looks like a bug that's introduced in the middle of some graphics refactor, I'll investigate

**Comment by slmjkdbtl** [comment]
(fixed)
