### ISSUE TITLE
Feature Request: Event trigger for when an object leaves the scene

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#52]
I know there's an exists() and an add() event. But need some kind of event or check to see if an object is still visible in a scene. For instance imagine if you are in a shooter game and enemies are spawing from the top and moving down. It would be great to have something like obj.leftView() = true and object.on("leftView", (o)=>{ destroy(o) } )  when the enemies go down below the view and offscreen, so they can be destroyed ( or whathaveyou )

If there already is something great, but I couldn't find it. And if there's not - this is a request to add this.

It's not when the object is invisible, but just when the object is now outside the viewport.

**Comment by slmjkdbtl** [comment]
There's currently not. If we're doing this by default for every object it'll be a bit costly (gotta run a matrix multiplication on every obj every frame to apply camera), I'll make an example with this as a custom component, and see if it's fit for a plugin, or even lib built-in. Thanks for the suggestion!

**Comment by slmjkdbtl** [comment]
Made an example of that [here](https://kaboomjs.com/examples#out)

**Comment by triptych** [comment]
Excellent! Thanks for looking into this

**Comment by triptych** [comment]
Looks like the example broke for some reason 
![image](https://user-images.githubusercontent.com/8691/120058710-c48ce380-c001-11eb-8fc2-ee69b274ee42.png)

**Comment by slmjkdbtl** [comment]
nice catch, fixed!
