### ISSUE TITLE
onUpdate and onDraw callbacks added without tags should be reset when changing scenes like all other callbacks

### ISSUE THREAD

**Issue by bacongravy** [replit/kaboom#531]
### Version

v2000.2.7

### What browsers are you seeing the problem on?

Safari

### What happened?

Sometimes when I add callbacks in a scene's initialization function, those callbacks continue to be called after switching to another scene. Specifically, callbacks added without tags using the global `onUpdate()` and `onDraw()` functions continue to be called, e.g callbacks added like this:

```
onUpdate(() => {})
```

### What's the expected behavior?

My expectation is that all callbacks added to the game when creating a scene will be removed when switching to another scene. This is true of all callbacks added to objects added to the scene (that don't have the `"stay"` tag).  This is true of all callbacks added to the game, **with tags**, using the global `on()` function. This is true of all callbacks added to the game, **with or without tags**, using `onClick()`. This is even true of all callbacks added to the game, **with tags**, using `onUpdate()`. The callbacks passed to any of these functions in one scene's initialization function stop being called after going to another scene. _It is only the callbacks added to the game, **without tags**, using `onUpdate()` and `onDraw()`, that do not stop being called._

I looked into why this is happening and the difference in behavior is due to `onClick()` using the `game` object to store the callback, and `onUpdate()`/`onDraw()` using the `game.root` object to store the callback (when no tag is passed).

Here's what I found. When passing in just a callback, **with no tag**:
* `onClick()` calls `game.on()`, which adds an element to the `game.events` object
* `onUpdate()` and `onDraw()` indirectly call `game.root.on()`, which adds an element to the `events` object captured by the closures returned by the `make()` function

What difference does this make? Well, whenever you call `go()`, the `game.events` and `game.objEvents` objects are reset to be empty objects, effectively canceling all of the callbacks added by the previous scene. But the same is not true of the `game.root` object -- it is in fact impossible to remove triggers added to the `game.root` object. So they continue to be triggered, even after scene changes.

The simplest workaround to this issue is to add an empty object to the scene and add the callback to that:

```
add([]).onUpdate(() => {})
```

This works because the callback gets added to object's `events` object, and the object gets destroyed when leaving the scene.

### Minimum reproducable code

```shell
// TO REPRODUCE, JUST CLICK TO CHANGE SCENES, TWICE.
// THE FIRST SCENE'S CALLBACKS ARE REMOVED AS EXPECTED.
// THE SECOND SCENE'S UPDATE CALLBACK IS NOT REMOVED.

import kaboom from "kaboom"

kaboom()

let sceneName = undefined

scene("red", () => {
  sceneName = "red"
  add([
      pos(0, 0),
      rect(width(), height()),
      color(255,0,0),
  ])
  // THIS WORKS AS EXPECTED
  onClick(() => {
    if (sceneName != "red") throw "NOT RED"
    go("blue")
  })
  // THIS WORKS AS EXPECTED
  add([]).onUpdate(() => {
    if (sceneName != "red") throw "NOT RED"
  })
})

scene("blue", () => {
  sceneName = "blue"
  add([
      pos(0, 0),
      rect(width(), height()),
      color(0,0,255),
  ])
  // THIS WORKS AS EXPECTED
  onClick(() => {
    if (sceneName != "blue") throw "NOT BLUE"
    go("red")
  })
  // THIS DOES NOT WORK AS EXPECTED
  onUpdate(() => {
    if (sceneName != "blue") throw "NOT BLUE"
  })
})

go("red")
```

**Comment by slmjkdbtl** [comment]
Thanks for reporting and diving in! It's exactly the problem. Went with of clearing events when scene change

**Comment by bacongravy** [comment]
🎉  🎉 🎉 What an amazing turnaround time! 🤯 Thank you so much!
