### ISSUE TITLE
How to name sprites from spritesheet

### ISSUE THREAD

**Issue by ipante** [replit/kaboom#55]
Hi there,

I can't see information in the doc about creating sprites from a spritesheet (to use as separate tiles in level() for example). All the examples use distinct image files, and the only mention about splitting a spritesheet is related to animation (anim, from, too). What's the right way to do it ?

Many thanks for your help !

**Comment by triptych** [comment]
I'm just another user but looking at the docs:
https://kaboomjs.com/#loadSprite
```
loadSprite("froggy", "https://replit.com/public/images/mark.png");

// slice a spritesheet and add anims manually
loadSprite("froggy", "froggy.png", {
    sliceX: 4,
    sliceY: 1,
    anims: {
        run: {
            from: 0,
            to: 3,
        },
        jump: {
            from: 3,
            to: 3,
        },
    },
});```
Returns a promise with this structure:
![image](https://user-images.githubusercontent.com/8691/120112133-71ae4b80-c129-11eb-9fef-6ce7b846f10a.png)

So you assign the loadSprite to a var then reference the sliced sprite element you want via the frames array.

**Comment by triptych** [comment]
![image](https://user-images.githubusercontent.com/8691/120112193-b76b1400-c129-11eb-9762-6079a72bb021.png)

**Comment by ipante** [comment]
Good idea, but I think LoadSprite() expects an src. Assigning a frame to a var doesn't solve the issue (or I'm missing something). A good option would be to define those sprites directly while loading the Tilesheet, via a "frames" object (like "anims") but I'm not convinced loadSprite allows this syntax.

**Comment by triptych** [comment]
You reference a frame from a sprite when you add it. See this example:
https://observablehq.com/@triptych/rpg-tiles-scatter-art-with-kaboom
```
 for(let i = 0; i< 112; i++){
      K.add([
        K.sprite("rpgtiles", {
          frame: i
        }),
        K.scale(4),
        K.pos(K.rand(0,420), K.rand(0,420))
      ])
    }
```

You could create an enum for the `frame: [val]` with names for the sprites but underneath that would be the numbers in the sheet.

**Comment by ipante** [comment]
Mmmh, sorry I still can't get it. What's wrong with this syntax ?

`kaboom({
	global: true,
	fullscreen: true,
	scale: 2,
	debug: true,
	clearColor: [0, 0, 0, 1],
});

loadRoot("../assets/images/");

// chargement des tuiles
const tuiles = loadSprite("tuiles", "tuiles.png", {
    sliceX: 13,
    sliceY: 6
});

scene("accueil", () => {

	const carte = addLevel([
		"=====",
		"  *  ",
		"  *  ",
		"  x  ",
		"  *  ",
		"  *  "
	], {
		width: 5,
		height: 6,
		pos: vec2(0, 0),
		"=": [
			sprite("tuiles",{
				frame : 5
			}),
			solid(),
			"block",
		],
		"*": [
			sprite("tuiles",{
				frame : 17
			}),
			solid(),
			"block",
		],		
		"x": [
			sprite("tuiles",{
				frame : 61
			}),
			solid(),
			"block",
		],
		" ": [
			sprite("tuiles",{
				frame : 12
			}),
			solid(),
			"block",
		]
	});
});

start("accueil");`
