### ISSUE TITLE
Changing scale value of actor object inside component method results in unwanted position change

### ISSUE THREAD

**Issue by juansrx** [replit/kaboom#555]
### Version

v2000.2

### What browsers are you seeing the problem on?

Chrome, Firefox

### What happened?

Good Evening

In my code I have an actor object "mario", when I change the value of the scale attribute inside the biggify() method to any value greater or equal to 2, for some unknown reason my sprite, or in the case of the link to the demo I provide, my rectangle also displaces to the right a lot. The biggify method was provided by a component of the mario object.

I appreciate any help you can give.

### What's the expected behavior?

I only want the size of my actor to change, as I said, with values like 1.9 or lower I have no issues

### Live demo

https://replit.com/@juansrx/YellowOpenWatchdog2

**Comment by szkuwa** [comment]
Add `origin('bot')` to your mario and it should work. 

I think its related to collision detection and when your sprite grows kaboom tries to push it out of other solid objects thats why it moves to the right. If you change the anchor using origin() it works like expected.

**Comment by juansrx** [comment]
@szkuwa I works perfectly!, thank you
