### ISSUE TITLE
Loop() function executes immediately and before returning EventCanceller

### ISSUE THREAD

**Issue by szkuwa** [replit/kaboom#558]
### Version

master

### What happened?

I'm using 2000.2.8 but master has the same code for loop() 

Trying to cancel loop immediately using event canceller function causes "x is not a function" if it happens in the first iteration.

### What's the expected behavior?

User function should be delayed and called after returning event canceller.

### Minimum reproducable code

```shell
kaboom()

let cancelLoop 
cancelLoop = loop(365 * 24 * 60, () => {
	cancelLoop()	
})
```

**Comment by slmjkdbtl** [comment]
Sorry for the late response.. In v3000 it's changed to return a [`EventController`](), which will be like

```js 
const ev = loop(365 * 24 * 60, () => {
	ev.cancel()	
})
```
