### ISSUE TITLE
Function randi() has incorrect type

### ISSUE THREAD

**Issue by l8doku** [replit/kaboom#559]
### Version

master

### What browsers are you seeing the problem on?

Chrome

### What happened?

I tried using Typescript with strict rules for a project. The code `const test = randi(1, 5)` gives an error: _Expected 0 arguments, but got 2.ts(2554)_

The hint for the function `randi()` says 

```
(method) KaboomCtx.randi(): number
rand() but floored to integer.
@example
randi(0, 3) // will give either 0, 1, or 2
```

You can see here that the type of `randi()` is a function that takes 0 arguments and returns a number as defined here https://github.com/replit/kaboom/blob/master/src/types.ts#L1417

### What's the expected behavior?

Function `randi()` should work with strict type checks. I understand there are other parts of Kaboom that don't work with them, but considering the types are correct everywhere else, as far as I can tell, this is most likely an error.

**Comment by slmjkdbtl** [comment]
Thanks. Fixed in a135e89
