### ISSUE TITLE
Feature request : ability to save and load state to storage

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#56]
Many game engines like Godot have a way for the game to save and load state. This feature request is to add some easy way for devs to save the game state and load it -- could be as easy as save("state",{ foo:bar}) and load("state")

See https://docs.godotengine.org/en/stable/tutorials/io/saving_games.html

One simple example might be to save the high score in a game and when the player comes back it shows the high score.

**Comment by slmjkdbtl** [comment]
Do you mean saving the entire game state or arbitrary data, also what kind of storage? 

With arbitrary save data and local storage it's trivial to `localStorage["gamedata"] = { score: "123", }`, but can build helpers on these.

**Comment by triptych** [comment]
Just some wrapper for localstorage -- as a syntactic sugar .

**Comment by storyfeet** [comment]
I'd like to be able to go to a "pause" scene, and then go back to the game scene, exactly as I left, it. Some kind of scene stack could work well for this , 
```js
let v = pushScene("pause", args...)

//in "pause"
popScene(someresult).

```

**Comment by slmjkdbtl** [comment]
@storyfeet Sorry I just saw this. I like this, I'll put that on TODO

**Comment by slmjkdbtl** [comment]
A storage helper will be added in v0.6 which will release soon

**Comment by slmjkdbtl** [comment]
There's `getData()` and `setData()` helper now in beta https://kaboomjs.com/#getData
