### ISSUE TITLE
angle dt() function is not working on safari browser

### ISSUE THREAD

**Issue by jamtechdev** [replit/kaboom#567]
### Version

v2000.2

### What browsers are you seeing the problem on?

Safari

### What happened?

  I wrote this line and aspect object rotation. It's working fine on Firefox and chrome  but not working on safari
  galaxyOrange.angle += dt() + 0.5
  is

### What's the expected behavior?

Object rotation

**Comment by slmjkdbtl** [comment]
What's the behavior of not working, It doesn't rotate?

Does [this example](https://kaboomjs.com/play?demo=add) work for you?

**Comment by jamtechdev** [comment]
Yes, it's working. I think I have some error on my side 
Thank you for helping.
