### ISSUE TITLE
text() with width set wraps, but cuts off words.

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#57]
the text object is  very cool! However when you set a width, it's not all that useful because the words are cut off. Can you add an option or fix the rendering so that if a word does not fit in the width, the whole word is carried over to the next line? 
![image](https://user-images.githubusercontent.com/8691/120113300-b092d000-c12e-11eb-9e34-bfb3cef39b51.png)

**Comment by triptych** [comment]
```scene_intro = ()=>{
  const obj = k.add([
    k.text(`
Welcome to Dot Matrix RPG! This is a demo game without much of a real purpose other than to show off Observable working with Kaboom JS and some nice sprites and music. 

`, 4, {
        width: 120, // wrap when exceeds this width (defaults to 0 no wrap)
        //font: "proggy", // font to use (defaults to "unscii")
    }),
    k.pos(10, 10)
]);
}```

**Comment by slmjkdbtl** [comment]
yep word breaking is not implemented yet, will do soon

**Comment by ipante** [comment]
> yep word breaking is not implemented yet, will do soon

Can't wait ! Thank you very much.

**Comment by slmjkdbtl** [comment]
should be done by 2f82f92
