### ISSUE TITLE
TypeError: e.then is not a function

### ISSUE THREAD

**Issue by kingofsponges** [replit/kaboom#580]
### Version

master

### What browsers are you seeing the problem on?

Chrome

### What happened?

so i was trying to load a sprite and instead of actually running the game it gets stuck at the loading bar
why did it get stuck? `TypeError: e.then is not a function at kaboom.ts:706:5`

### What's the expected behavior?

it should just load without any problems

### Minimum reproducable code

```js
load("grass", "sprites/grass.png")
```

**Comment by l8doku** [comment]
Sprites are loaded with the function `loadSprite()` https://kaboomjs.com/#loadSprite

Function `load()` adds a loader, which is supposed to be a Promise, which has a method `.then` https://kaboomjs.com/#load

**Comment by kingofsponges** [comment]
oh alright

**Comment by kingofsponges** [comment]
closed
