### ISSUE TITLE
Error: failed to load burp bug 

### ISSUE THREAD

**Issue by BestSpark687090** [replit/kaboom#585]
When I try to load up an empty Kaboom game, it is giving me the error: “Error: failed to load burp.” But I have nothing in the project. What’s wrong with it?

**Comment by 8xu** [comment]
Where are you "loading" an empty Kaboom game?

**Comment by lajbel** [comment]
the best bug name.

it may be due to your browser or your internet connection, but tga can probably help you to detect the problem. If you can reopen the issue using the template that would be great

**Comment by slmjkdbtl** [comment]
What browser are you using? Are you able to load any other audio file?

Maybe your browser doesn't support certain web audio api. But anyway since it's loaded by default I changed it to not block the game in future versions.

**Comment by BestSpark687090** [comment]
bro it’s been 4 months im not sure about loading audio files, I wasn’t loading any.also I was using vs code live previewOn Sep 25, 2022, at 9:33 PM, tga ***@***.***> wrote:﻿
What browser are you using? Are you able to load any other audio file?
Maybe your browser doesn't support certain web audio api. But anyway since it's loaded by default I changed it to not block the game in future versions.

**Comment by lajbel** [comment]
For load audios you can do

```js
/// use any file path you have
loadSound("n", "music.mp3");
play("mp3");
```

Anyway, in `@next` versio this no longer block game. Reopen if you have the same bug playing audios

**Comment by BestSpark687090** [comment]
There's a problem with that. I wasn't loading *any *audio files at all. It
was a blank project, and i never tried to load anything.
