### ISSUE TITLE
Net Example is not working

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#59]
Visit https://kaboomjs.com/examples#net

See screen

![image](https://user-images.githubusercontent.com/8691/120247778-8e31ad00-c229-11eb-9036-ca3466c6be43.png)

And console:

![image](https://user-images.githubusercontent.com/8691/120247811-a5709a80-c229-11eb-8155-ce512773bf75.png)

**Comment by slmjkdbtl** [comment]
this example is not supposed to work yet (i can add a comment on top to clarify later)
