### ISSUE TITLE
Out Example not working

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#60]
Visit https://kaboomjs.com/examples#out

clicking does nothing. Blank screen.

console:

![image](https://user-images.githubusercontent.com/8691/120247903-f84a5200-c229-11eb-908e-e7e23dff6955.png)

**Comment by slmjkdbtl** [comment]
weird, but solved now, thx

**Comment by triptych** [comment]
Thanks for looking so quickly! You rock!
