### ISSUE TITLE
Outline missing corners

### ISSUE THREAD

**Issue by Meldiron** [replit/kaboom#607]
### Version

v2000.2.9

### What browsers are you seeing the problem on?

Chrome

### What happened?

I created a simple rectangle with the same background as the game background (to look divisible), and added a white outline.

First, it just looked like rounded corners because the outline was too slim, but by increasing the size I noticed the corners are not rendered:

<img width="649" alt="CleanShot 2022-06-26 at 21 33 04@2x" src="https://user-images.githubusercontent.com/19310830/175830926-19134f86-5894-4e5c-823c-861aad983f97.png">

### What's the expected behavior?

Filled corners. If possible, a cool feature would be allowing rounding these corners (by making arc).

### Minimum reproducable code

```shell
const g = kaboom({ background: [19, 13, 33] });

		const w = g.width();
		const h = g.height();

		add([
			pos(w / 2, h / 2),
			rect(100, 100),
			outline(20, g.Color.fromArray([255, 255, 255])),
			area(),
			g.origin('center'),
			color(19, 13, 33)
		]);
```

**Comment by slmjkdbtl** [comment]
Changed the default line join to rounded in f7c5189169e1184052cfb1bf849f094e496dd366
