### ISSUE TITLE
Support for ascii symbols like "♥" in text?

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#62]
Not sure if this is a bug or a feature request.

I was working on an RPG where I wanted to show the heart symbol in text ( yes I know I could do images, but this was faster for the implementation ) But when I tried to render ascii symbols - nothing showed up... is this a limitation of the engine or of the font?

Example replit : https://replit.com/@triptych/DeafeningDesertedAdmins#scenes/main.js

```
add([
  text("ascii text? Heart: ♥"),
  pos(10,10)
])
```
![image](https://user-images.githubusercontent.com/8691/120248512-5bd57f00-c22c-11eb-873e-5a590a8ea03f.png)

**Comment by slmjkdbtl** [comment]
The default font is [unscii](http://viznut.fi/unscii/) which doesn't contain this character, however there's a built-in plugin for [CP437](https://en.wikipedia.org/wiki/Code_page_437) font which contains multiple special game-like characters including the heart:

```html
<script src="https://kaboomjs.com/lib/latest/plugins/cp437.js"></script>
```
or
```
import cp437Plugin from "kaboom/plugins/cp437"
```
and
```js
const k = kaboom({
    plugins: [ cp437Plugin ],
});

k.loadCP437();

add([
    text("♥", { font: "cp437" }),
]);
```

**Comment by triptych** [comment]
I tried this using a local PNG as well as a remote bitmap font, but it doesn't seem to work. 

https://observablehq.com/@triptych/kaboom-0-5-1-load-font

**Comment by slmjkdbtl** [comment]
you'll have to define what's in that bitmap font as the last argument, or it'll fallback to [standard ascii chars](https://github.com/replit/kaboom/blob/b55f2168a05494fe48f94b1d1eff9a2f41155172/src/assets.ts#L65), there's an example of that [here](https://github.com/replit/kaboom/blob/b55f2168a05494fe48f94b1d1eff9a2f41155172/examples/text.js#L11)

**Comment by triptych** [comment]
Thank you for the additional info. I tried to import the same png that you use, and use the same code. But in my case it's still not loading :( 

https://observablehq.com/@triptych/kaboom-0-5-1-load-font

**Comment by slmjkdbtl** [comment]
oh, the second argument to `text()` is actually the size, the third argument is the additional configs including `font`

**Comment by triptych** [comment]
Thank you! That totally worked!

**Comment by slmjkdbtl** [comment]
Nice. Also fyi text objects do automatically have colliders (`area()`), but right now they're only calculated on creation, so it won't update automatically when you update `obj.text =  "oh hi"` yet.
