### ISSUE TITLE
Accented characters missing in native fonts

### ISSUE THREAD

**Issue by ipante** [replit/kaboom#626]
### What browsers are you seeing the problem on?

Chrome

### What happened?

All accented characters (à,é, etc.) are missing in the native fonts.

### What's the expected behavior?

Have the accents rendered.

**Comment by lajbel** [comment]
I recommend adding your own font. The default fonts do not contain these characters but may do so in the future, thank you

**Comment by ipante** [comment]
Thanks for your answer. Adding a font is already our workaround, but I really think it should be native : I'm using Kaboom in an educational setting (University) and having to explain that we'll have to manually add such a native feature is quite... meh.

**Comment by slmjkdbtl** [comment]
The next version of Kaboom supports all fonts that browser support (built-in fonts, `.ttf` `.otf`, `.woff` etc. These changes are also published in `kaboom@next` (this is a dev release and might also contain breaking change)

**Comment by ipante** [comment]
Purrfect ! Thanks !
