### ISSUE TITLE
Feature Request: Site--> Add link to forums

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#63]
When I go to kaboomjs.com I am able to use and play with repls and learn how to use, but there's no way for me to know what the right forums are to share games and stuff. 

Can you add a link to the right forums on the site? Something like https://replit.com/talk/all?q=kaboomjs&lang=kaboom I guess?

**Comment by slmjkdbtl** [comment]
Kaboom doesn't have an official forum yet, but might have in near future, definitely will link when there's an official one.

**Comment by slmjkdbtl** [comment]
I'll add a link to github discussions
