### ISSUE TITLE
KaboomOpt# Letterbox not working

### ISSUE THREAD

**Issue by BMOTheGhost** [replit/kaboom#636]
### Version

v2002.2.9

### What browsers are you seeing the problem on?

Chrome

### What happened?

I'm trying to use the lettebox option inside of `kaboom()` initialization. I have tried several different ways of using it but it doesn't seem to work, it only scales the canvas instead of scaling all items inside of the canvas. Could I have some help if this isn't a bug, and if so then this is just a bug report.
```      import kaboom from "kaboom"
kaboom({
  letterbox: true,
  height:576,
  width:1024,
});

### What's the expected behavior?

It should fit to the screen with a 16:9 aspect ratio (or in other words just scale my current resolution), to the max amount it can when the site is pulled up, scaling everything else in the canvas along with it.

### Minimum reproducable code

kaboom({
  letterbox: true,
  height:576,
  width:1024,
});

loadSprite("image", "sprites/image.png");

add([
  sprite("image"),
  pos(width() / 2, height() / 2),
  origin("center"),
]);
```

### Live demo

https://osumania-kaboom-ver.emiiy.repl.co/

**Comment by lajbel** [comment]
Yeah for the expected work you should use

```js
kaboom({
    stretch: true,
    letterbox: true,
})
```
