### ISSUE TITLE
Feature Request: full docs beyond the anchors on the home page

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#64]
Having the docs on the home page is great! But as someone who's using this every day for a week now, having to mouse over some API elements as the only way to know how some things work is a bit challenging. 

For instance. I'm on my laptop with a limited screen space, and I'm trying to look at `KaboomCtx`:
![image](https://user-images.githubusercontent.com/8691/120248975-2598ff00-c22e-11eb-9361-2a3766797ca7.png)

It's literally impossible for me to see the whole thing because when I mouse over the `KaboomCtx` I only see the partial tooltip, and there's no way to anchor it to scroll. 

Sure I can go look in the source - but having something more reader friendly ( outside the fun main website ) would be awesome.

**Comment by slmjkdbtl** [comment]
For sure, I'll add a quick page for them later soon (the docs are all very wip)

**Comment by slmjkdbtl** [comment]
Added a route that dumps basic type info: https://kaboomjs.com/type/GameObj

**Comment by slmjkdbtl** [comment]
Now all types have their place in the new page. Still missing individual field documents atm, but not the scope of this issue, closing this one.
