### ISSUE TITLE
Documentation: Intro link serving 404

### ISSUE THREAD

**Issue by rmhs345** [replit/kaboom#668]
### What browsers are you seeing the problem on?

Chrome, Firefox, Safari, Microsoft Edge

### What happened?

When clicking on the `intro` link within the https://kaboomjs.com/doc/setup page
I was brought to a 404 page when I expect to be served this md file: https://github.com/replit/kaboom/blob/master/doc/intro.md
![image](https://user-images.githubusercontent.com/46785810/212230586-c6ef3c20-7cda-49f8-9618-8c9a7bc4b143.png)

I believe this is caused because the link is going to the `intro.md` and not `intro`:
![image](https://user-images.githubusercontent.com/46785810/212230794-3249b5e3-da2c-4ef6-9970-59a7132ec062.png)

Example shown on the main page:
![image](https://user-images.githubusercontent.com/46785810/212230967-c6968ca6-b8a2-40a7-b464-4f0323279e8c.png)

### What's the expected behavior?

To be served the intro.md page

**Comment by slmjkdbtl** [comment]
Does it still 404 for you? It seems to work for me now

**Comment by hacknug** [comment]
Perhaps they're looking at the v3000 docs? This link doesn't work for me either: https://kaboom.replit.repl.co/doc/intro

**Comment by rmhs345** [comment]
Greetings, 

The 404 still persist on https://kaboomjs.com/doc/setup ( Don't know what `ver` the doc is )

When clicking on the link within Lighter Template `intro tutorial`, you will be redirected to a 404 page.
![image](https://user-images.githubusercontent.com/46785810/215619175-105c7ea2-d78e-4da1-ad69-1c77e3da8050.png)
![image](https://user-images.githubusercontent.com/46785810/215619301-4e640309-c21e-4aca-af38-56d831e0ab40.png)

This is due to us redirected the user to `intro.md`, rather than `intro`

I hope this clarify the issue.

**Comment by hacknug** [comment]
Seems to be working fine now. Can you confirm @rmhs345 ?

**Comment by hacknug** [comment]
Just opened a PR that should address the issue (perhaps not for non-beta docs if those are not being deployed anymore)
