### ISSUE TITLE
pausing works as stop after music loops

### ISSUE THREAD

**Issue by llermaly** [replit/kaboom#674]
If loop is set to true, after the first loop when you pause and then play, the song will start again instead of resuming.

Wait for the song to repeat, pause/resume and the song will reset instead of resuming.

```
// audio playback & control

kaboom()

loadSound("kaboom2000", "/sounds/kaboom2000.mp3")

// play() to play audio
// (This might not play until user input due to browser policy)
const music = play("kaboom2000", {
	loop: true,
})

// Adjust global volume
volume(0.5)
 
// Adjust music properties through input
onKeyPress("space", () => {
	if (music.isPaused()) { 
		music.play()
	} else {
		music.pause()
	}
})
```

**Comment by llermaly** [comment]
The reason I guess is because after looping time adds up instead of restarting so music.play(music.time()) do not work.

**Comment by slmjkdbtl** [comment]
Yes the time tracking doesn't reset on loop, it's a bug, will fix soon

**Comment by slmjkdbtl** [comment]
Made `time()` by default `% duration()` as a temp workaround 70b8592
