### ISSUE TITLE
Are there docs somewhere about methods not in the docs?

### ISSUE THREAD

**Issue by ogrotten** [replit/kaboom#682]
I was initially curious about `addLevel().spawn()` and the parameters etc, but it's not on the docs site. I looked at the source for this, and there's quite a bit of info that isn't in the docs.

Is there a more comprehensive set of docs out there?

If not, here's a suggestion: Get a couple of local high schoolers to translate the types/methods to doc format.

And also sort things. Never can tell if a method exists until you look at the entire list, just in case the method you're looking for is the last item show.

**Comment by lajbel** [comment]
You are checking the last kaboom.js documentation? Respective to the new features. Now, `spawn` is from `LevelComp` component.
