### ISSUE TITLE
The Kaboom 3000 migration guide in the beta release announcement is slightly misleading

### ISSUE THREAD

**Issue by DrRman25** [replit/kaboom#687]
The Kaboom 3000 [migration guide](https://3000.kaboomjs.com/blog/3000#migrating-to-v3000) says, "`solid()` comp becomes an option in `body({ isSolid: true })`," but this is incorrect. It has changed to `body({ isStatic: true })`, not `body({ isSolid: true })`. If you could please fix this, that would be great, since it confused me when I tried to migrate my game to Kaboom 3000, and I'm pretty sure some beginners, in the future, might be confused by that as well. Thanks in advance!

![Screenshot 2023-02-27 205422](https://user-images.githubusercontent.com/104178011/221757677-182e0350-5d56-41f2-a49f-84529b9fdf46.png)

**Comment by lajbel** [comment]
Fixed in 8d6ac55.
