### ISSUE TITLE
Question: Angle is in what? (Degrees or Radians)

### ISSUE THREAD

**Issue by Beanzilla** [replit/kaboom#69]
Hi there kaboom community,

  I am trying to make a 2d top-down shooting game... but I am besides myself stuck on what the angle is of an object.

  Another good question I will have is (assuming it's degrees), how do I increment it by a single degree?

I have the math to convert the angle in degrees to a vec2 of x and y, that I will apply to my "bullet" to make it move in the direction it was fired from. (I just need to know how to get an exact/or close enough, angle in degrees from an object to use my math on it to get a more realistic bullet trajectory)

In the future of my game I am thinking of maybe even using the mouse to "aim" but for now everything is basic keybindings.

If you need any further information I will gladly provide it.

**Comment by triptych** [comment]
Can  you post an example project? Can help.

**Comment by slmjkdbtl** [comment]
It's brought by the `rotate()` component. There's [this example](https://kaboomjs.com/examples#transform) that changes angle.

**Comment by Beanzilla** [comment]
> Can you post an example project? Can help to explain what you are trying to do.

A general idea is for something (similar **NOT** identical) is the web game [diep.io](http://diep.io/) minus all the multi-player stuff.

**Comment by Beanzilla** [comment]
> It's brought by the `rotate()` component. There's [this example](https://kaboomjs.com/examples#transform) that changes angle.

So `obj.angle += 1` rotates exactly 1 degree? I want the angle to change based on keyDown not time.

**Comment by Beanzilla** [comment]
Sorry for the delay is responding, I forgot to check my github on this.

**Comment by slmjkdbtl** [comment]
`angle` is in radians, there is actually an undocumented `deg2rad(deg: number) => number` helper function for that for convenience.

**Comment by Beanzilla** [comment]
Ah, ok... so I could just take my cosine and sine from that to get my vec2 of x,y for my bullet then... (And I use the deg2rad to rotate by X degrees?)

**Comment by Beanzilla** [comment]
Ok, confirmed it with the example you gave me... does exactly what I was looking for. (Thank you for helping)

**Comment by slmjkdbtl** [comment]
Are you trying to calculate the vector from an angle? Yeah if you're using degrees it'll be something like
```js
function vec2FromAngle(a: number): Vec2 {
	return vec2(Math.cos(deg2rad(a)), Math.sin(deg2rad(a)));
}
```
(there's something similar used internally, maybe i should export it...)

Glad it helped!

**Comment by Beanzilla** [comment]
> Are you trying to calculate the vector from an angle? Yeah if you're using degrees it'll be something like
> 
> ```js
> function vec2FromAngle(a: number): Vec2 {
> 	return vec2(Math.cos(deg2rad(a)), Math.sin(deg2rad(a)));
> }
> ```
> 
> (there's something similar used internally, maybe i should export it...)
> 
> Glad it helped!

Well now that I know that obj.angle is in radians I just need to make

```js
function vec2FromAngle(a: number): Vec2 {
	return vec2(Math.cos(a), Math.sin(a));
}

function spawnBullet(obj) {
  add([
    rect(3, 3),
    pos(obj.pos),
    {
       vel: vec2FromAngle(obj.angle)
    },
    'bullet'
  ])
}
```

Now I would pass player to spawnBullet and it should apply bullet.vel attribute so when I move it will look like

```js
action('bullet', (b) => {
  b.move(b.vel[0], b.vel[1])
})
```

Assuming my math is right on that and I didn't transpose/mistype anything. :)

ka :boom: .js

**Comment by slmjkdbtl** [comment]
> b.move(b.vel[0], b.vel[1])

maybe a typo here? `vec2` is `{ x: number, y: number }` instead of array

**Comment by Beanzilla** [comment]
Ooops, Yeah I always get that mixed up... I keep thinking it's a c++ vector or python list... but it's not.

So it really would be?

`b.move(b.vel.x, b.vel.y)`

**Comment by slmjkdbtl** [comment]
Yep! Or just `b.move(b.vel)`

**Comment by Beanzilla** [comment]
Ah, didn't help that my barrel.png was being rendered the wrong way.

Meh, but looks like everything works. (Again, Thank you very much)
