### ISSUE TITLE
Animations not playing past 2 frames

### ISSUE THREAD

**Issue by srobertson421** [replit/kaboom#7]
When creating animations via `loadSprite`, the library only cycles up to the second index in the frames array even if there are more frames.

#6

**Comment by srobertson421** [comment]
Not actually an issue, `loadSprite` animation declaration actually looks for an array range, rather than each individual frame number:

Incorrect
```
loadSprite('explosion', '/assets/explosion.png', {
  sliceX: 4,
  sliceY: 4,
  anims: {
    explode: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  }
});
```
Correct
```
loadSprite('explosion', '/assets/explosion.png', {
  sliceX: 4,
  sliceY: 4,
  anims: {
    explode: [0,15]
  }
});
```

**Comment by slmjkdbtl** [comment]
Thanks for doing the clarification here! I'll make this clearer in the docs also
