### ISSUE TITLE
Feature request: Touch events for mobile devices

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#70]
There are things like click and mousemove, but would be great to have a suite of events for mobile devices -- touch, orientation, etc.

https://developer.mozilla.org/en-US/docs/Web/API/Touch_events
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent

**Comment by slmjkdbtl** [comment]
Kaboom has been translating touch events to mouse events, so `mouseClick()` and `mouseMove` will be translated to `touchstart` and `touchmove` under the hood so you don't need to write 2 sets of input for desktop and mobile, but I'll also make that configurable and add explicit touch event in v0.6 which will be released soon.

**Comment by slmjkdbtl** [comment]
There are touch events now on beta
