### ISSUE TITLE
kaboom option scale has an issue.

### ISSUE THREAD

**Issue by qsun81** [replit/kaboom#701]
Hi,
Apparently, in v3000, when kaboom is initialized with options of width and height values and adding scale value that is not 1, canvas size and game elements correctly changes according to the scale option.  However,  when debug.inspect = true, hovering over the area where the game elements were originally located when scale was 1, element description pops up.   This phenomenon was found when onClick event was applied to a game object with kaboom scale option, and the event was registered outside of the the area of the game element sprite.
Playground for v3000 shows the issue, but playground for v2000 didn't have problem.    The following code was used to test the phenomenon.  

```
kaboom({
	width: 1200,
	height: 600,
	scale: 0.4,
})

loadSprite("bean", "/sprites/bean.png")

const player = add([
	sprite("bean"),   
	pos(120, 80),    
	rotate(0),
	anchor("center"),
	area(),
	"player"
])

onClick("player",()=>{
	debug.log("clicked")
})

debug.inspect = true;
```

**Comment by slmjkdbtl** [comment]
Yeah that's a regression, 54ba685ef02542ee619433f62dab80840979886f this should fix it
