### ISSUE TITLE
keyPress Time Question

### ISSUE THREAD

**Issue by loretod** [replit/kaboom#71]
Since there isn't an official forum to post these noob questions on yet... I'll just go ahead and embarrass myself here. I'm a big fan of the Replit and Kaboom mix so far!

I have beginner questions about how to run an action for a set period of time after a keypress. For example:
`keyPress("space", () => {
  bill.action(() => {
    bill.angle += dt();
  });
});`

If this could rotate bill for 2 seconds and stop. I tried adding an `await wait(2);` but get an async function only error but I don't really want it to wait or loop correct.?  I don't think action() take a time argument? 

Any help would be most appreciated!

**Comment by triptych** [comment]
One way to think about it is if you have some variable "running" which is false by default.
in an action you check to see if "running" is true, if so , then do your angle change.
Now when you click the space bar - set "running" to true, and set a wait for some time to set it to false.
every frame, that action will be checking the value of "running" and either keep changing the angle or not.

So what I mean is have some action that runs every frame, but it checks some var to see if it should "run" this frame.
Then just have that var be false by default, and true for some small time frame. 
While it's true, your action will run, then stop again when your timer sets the var to false again.

**Comment by loretod** [comment]
Ah gotcha... thanks so much for the explainer. Makes sense. I wasn't sure if there was a baked-in method that does just that. It would be great to have a Discord or Slack server to chat and share. Maybe down the line.
