### ISSUE TITLE
Playground and Blog 500 error. Intro 400 error.

### ISSUE THREAD

**Issue by onurusluca** [replit/kaboom#718]
https://kaboomjs.com/play
https://kaboomjs.com/blog
![image](https://github.com/replit/kaboom/assets/51825926/ba3a7481-36ee-44e9-b858-d878eab1fd48)

https://kaboomjs.com/doc/intro
![image](https://github.com/replit/kaboom/assets/51825926/820ed4d3-7474-4895-8404-8125c4f18b8a)

**Comment by lajbel** [comment]
Fixed!
