### ISSUE TITLE
scale option for kaboom() initialization is not working properly.

### ISSUE THREAD

**Issue by qsun81** [replit/kaboom#724]
When the scale is reduced to a value less than 1, the game screen seems to be reducing correctly, but the entire game is not fitting into the reduced game screen, and it's rather chopped off.  

The image below is when scale is 1, and the following is when it is 0.4.  
![scale 1](https://github.com/replit/kaboom/assets/73376092/c5dd9ccc-0606-4fc9-ae3d-6c500aac2668)

![scale 0 4](https://github.com/replit/kaboom/assets/73376092/fb3f2ef8-baad-4d60-8f91-60b77560d65d)

I tried it on the kaboom playground, "platformer".

**Comment by slmjkdbtl** [comment]
Can you try if 3000.0.5 fixes the issue?
