### ISSUE TITLE
combine with react?

### ISSUE THREAD

**Issue by dcsan** [replit/kaboom#74]
this looks pretty neat! I have a larger web app all built out with react, and wanted to use kaboom for a single page game. Was wondering how best to do this?

Worried if there are context or router changes that would force re-rendering, otherwise break the kaboom content, or ways to "suspend" react from controlling the same parts of the DOM.

**Comment by triptych** [comment]
If you are concerned React could accidentally nuke your game, you could put the game in a statically rendered iframe.
Sounds like you should investigate on the React side.
Perhaps post a sample page with a game running and see if you run into problems.
https://github.com/facebook/react/issues/10923#issuecomment-338715787

**Comment by oknoorap** [comment]
@dcsan it should be in separate repository. The possible approach would be using react reconciler.
https://www.youtube.com/watch?v=CGpMlWVcHok

**Comment by slmjkdbtl** [comment]
Are you experiencing real problems? The kaboom state should be safe, if you're using `global` all globals functions should refer to the same kaboom state, if you're using `const k = kaboom` then you might want want to put it behind a ref. Also you definitely don't want to call `kaboom()` again during a game so it should be in a place where it's only run on mount.

I can do some investigation and make a good template for react use.

**Comment by dcsan** [comment]
no, I was inquiring before I started the dev effort. @slmjkdbtl  I thought since react is popular you might already have an answer.

**Comment by slmjkdbtl** [comment]
It should be the same as how you'd use any JavaScript library with react:

```tsx
import kaboom from "kaboom"
import * as React from "react"

const Game: React.FC = () => {

	const canvasRef = React.useRef(null)

	// just make sure this is only run once on mount so your game state is not messed up
	React.useEffect(() => {

		const k = kaboom({
			// if you don't want to import to the global namespace
			global: false,
			// if you don't want kaboom to create a canvas and insert under document.body
			canvas: canvasRef.current,
		})

		k.add([
			k.text("oh hi"),
			k.pos(40, 20),
		])

		// write all your kaboom code here

	}, [])

	return <canvas ref={canvasRef}></canvas>

}
```

Please reopen if there's any other question about using with react!

**Comment by xtawfeeq7k** [comment]
Hello @slmjkdbtl (sorry for the ping), I am having some issues when I am trying to load sprites in my react-kaboom project
<h2>output:</h2>

![image](https://user-images.githubusercontent.com/87164562/182834664-fb4cdb71-3101-4a19-8378-fcc7ed65901c.png)

<h2>console:</h2>

![image](https://user-images.githubusercontent.com/87164562/182835049-6248d068-49ff-4d78-8c90-db8cdd7a239b.png)

<h2>my code:</h2>

![image](https://user-images.githubusercontent.com/87164562/182834822-f584542d-9abc-4515-b97a-dadd66528d58.png)

**Comment by peratik** [comment]
```
import { useEffect, useRef } from "react";
import kaboom, { KaboomCtx, KaboomOpt } from "kaboom";

const Kaboom = ({run, options} : {run: (kaboom: KaboomCtx) => void, options?: KaboomOpt}) => {
    const isRunning = useRef(false);
    const canvasRef = useRef<HTMLCanvasElement>(null);
        
    useEffect(() => {
        if (isRunning.current || !canvasRef || !canvasRef.current) {
            return;
        }
        isRunning.current = true;
        run(kaboom({
            ...options,
            global: false,
            canvas: canvasRef.current as HTMLCanvasElement,
        }))
    }, [options, run])

    return <canvas ref={canvasRef} className={styles.canvas}></canvas>
}

export default Kaboom
```

**Comment by ganevdev** [comment]
> It should be the same as how you'd use any JavaScript library with react:
> 
> ```tsx
> import kaboom from "kaboom"
> import * as React from "react"
> 
> const Game: React.FC = () => {
> 
> 	const canvasRef = React.useRef(null)
> 
> 	// just make sure this is only run once on mount so your game state is not messed up
> 	React.useEffect(() => {
> 
> 		const k = kaboom({
> 			// if you don't want to import to the global namespace
> 			global: false,
> 			// if you don't want kaboom to create a canvas and insert under document.body
> 			canvas: canvasRef.current,
> 		})
> 
> 		k.add([
> 			k.text("oh hi"),
> 			k.pos(40, 20),
> 		])
> 
> 		// write all your kaboom code here
> 
> 	}, [])
> 
> 	return <canvas ref={canvasRef}></canvas>
> 
> }
> ```
> 
> Please reopen if there's any other question about using with react!

In this case, the user effect will continue to work even if the component is unmounted. It’s better to write a return, although I haven’t figured out which one. As an option:

```
return () => {
  k.debug.paused = true;
};
```
Pauses the game.

Or:
```
k.scene("endGame", () => {});
return () => k.go("endGame");
```
Create an empty scene "endGame" and call it.

I don’t know, I’m not sure that these are the best options, but I couldn’t think of a better one.

**Comment by Shubh-Rajawat** [comment]
This is my code I am just making a simple jump-the-pillar . here I have created an obstacle in which I applide 
move() function it accepts two parameters **`move(direction , speed)`**  but it is not moving .
Any help is Appreciated.

```

import { useEffect } from 'react';
import './App.css';
import kaboom from "kaboom";
function App() {

  useEffect( () => {
    let boom = kaboom();
    console.log( "kaboom->", boom )

    boom.setGravity( 1000 )
    boom.loadBean()

    const player = boom.add( [
      boom.sprite( "bean" ),
      boom.pos( 120, 80 ),
      boom.area(),
      boom.body(),
    ] )

    const platform = boom.add( [
      boom.rect( 2000, 48 ),
      boom.pos( 0, 950 - 48 ),
      boom.outline( 4 ),
      boom.area(),
      boom.body( { isStatic: true } ),
      boom.color( 127, 200, 255 ),
    ] )

    const obstacle = boom.add( [
      boom.rect( 48, 64 ),
      boom.area(),
      boom.outline( 4 ),
      boom.pos( 400, 950 - 48 ),
      boom.anchor( "botright" ),
      boom.color( 255, 180, 255 ),
       boom.move( "LEFT", 10 ),  // <-- **!!PROBLEM!!**  I am getting problem here
      "tree",
    ] );
    player.onCollide( "tree", () => {
      boom.addKaboom( player.pos );
      boom.shake();
    } );

    boom.onKeyPress( "space", () => {
      player.jump()
    } )
    boom.onKeyPress( "up", () => {
      player.jump()
    } )
    boom.onKeyPress( "right", () => {
      player.move( 1000 )
    } )
    boom.onKeyPress( "left", () => {
      player.move( -1000 )
    } )

  }, [] )

  return (
    <></>
  );
}


export default App;

```
