### ISSUE TITLE
'default' is not exported by kaboom.js

### ISSUE THREAD

**Issue by DecampsRenan** [replit/kaboom#75]
I tried to use kaboom in a typescript project setup with [vite](https://vitejs.dev/); however it seems that the default import from kaboom is an empty object:

The error thrown on production build:
```
~/Documents/dev/games/flappy-like main
❯ yarn build
yarn run v1.22.10
warning package.json: No license field
$ tsc && vite build
vite v2.3.7 building for production...
transforming (2) src/main.tsError when using sourcemap for reporting an error: Can't resolve original location of error.
✓ 3 modules transformed.
'default' is not exported by node_modules/kaboom/dist/kaboom.js, imported by src/main.ts
file: /Users/renan/Documents/dev/games/flappy-like/src/main.ts:1:7
1: import kaboom from "kaboom";
          ^
2: const k = kaboom();
3: k.scene("start", () => {
error during build:
Error: 'default' is not exported by node_modules/kaboom/dist/kaboom.js, imported by src/main.ts
    at error (/Users/renan/Documents/dev/games/flappy-like/node_modules/rollup/dist/shared/rollup.js:7917:30)
    at Module.error (/Users/renan/Documents/dev/games/flappy-like/node_modules/rollup/dist/shared/rollup.js:9859:16)
```

Browser error on dev:
<img width="532" alt="CleanShot 2021-06-09 at 18 24 51@2x" src="https://user-images.githubusercontent.com/7521065/121392815-0433c380-c950-11eb-96c5-6f235b9a1929.png">

I don't know if I'm missing something in the vite config or typescript config:

The `main.ts` file:
```ts
import kaboom from 'kaboom'

const k = kaboom() // ⚠️ Throw an error "Uncaught TypeError: kaboom is not a function"

k.scene('start', () => {
  // add a text at position (100, 100)
  k.add([
    k.text("ohhimark", 32),
    k.pos(100, 100),
  ]);
})

k.start('start')
```

tsconfig.json file
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "lib": ["esnext", "DOM"],
    "moduleResolution": "node",
    "strict": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "esModuleInterop": true,
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noImplicitAny": false,
    "isolatedModules": true,
    "typeRoots": [
      "node_modules/**/*.d.ts"
    ],
  },
  "include": ["./src/*.ts"]
}
```

**Comment by DecampsRenan** [comment]
I created a repo so it will be easier to see the issue: https://github.com/DecampsRenan/kaboom-no-default-export

Just install dependencies, run `yarn dev` and open you browser devtools or try to run `yarn build` to see the errors I mentioned

**Comment by rainkinz** [comment]
I'm having the same issue. Tried with just javascript and typescript, using parcel the error I get is:

```
Uncaught TypeError: _kaboom.default is not a function
    parcelRequire<["kaboom.ts"]< kaboom.ts:6
    newRequire main.c39d6dcf.js:47
    localRequire main.c39d6dcf.js:53
    parcelRequire<["main.ts"]< main.ts:1
    newRequire main.c39d6dcf.js:47
    parcelRequire main.c39d6dcf.js:81
    <anonymous> main.c39d6dcf.js:120
```

**Comment by franselles** [comment]
Hello.

I have solved the problem using full path to kaboom packages.
Using vite and vanilla javascript, not typescript.

`import kaboom from '../node_modules/kaboom/dist/kaboom';`

With typescript must use .d.td module.

**Comment by slmjkdbtl** [comment]
Looks like vite (is it using rollup?) is ignoring the `exports` field in kaboom's `package.json`. 

```json
"browser": "dist/kaboom.js",
"types": "dist/kaboom.d.ts",
"exports": {
	".": {
		"import": "./dist/kaboom.mjs",
		"require": "./dist/kaboom.cjs"
	},
	"./plugins/*": {
		"import": "./dist/plugins/*.mjs",
		"require": "./dist/plugins/*.cjs"
	}
},
```

I only tested package with `esbuild` and it works. I'll investigate into this, but if anyone is familiar with distributing packages for all `cjs`, `umd` and `iife` help is appreciated!

**Comment by micheg** [comment]
With parcel:
import kaboom from "../node_modules/kaboom/dist/kaboom.mjs";

**Comment by slmjkdbtl** [comment]
adding the `module` and `main` field to point to the `.mjs` and `.cjs` (8055546)  seems to fix this, can anyone verify by cloning and installing the library locally? (it's possible your code might break due to other hanging breaking changes on master which is unrelated to this)

**Comment by DecampsRenan** [comment]
I tested it and it works too @slmjkdbtl ! adding .mjs and .cjs versions fixes the issue 👍 

In my case I was able to bypass this issue (for vitejs) by adding an alias pointing to the kaboom package:
```js
alias: {
      kaboom: path.resolve(projectRoot, 'node_modules/kaboom/dist/kaboom.mjs'),
}
```

But I confirm that adding the `module` and `main` fields is working fine

**Comment by cn-80** [comment]
with react-scripts and a create-react-app project, the following worked for me:

```
import kaboom from "../node_modules/kaboom/dist/kaboom.mjs";
```

the file is a plain JavaScript file, I was not able to get it working with TypeScript

**Comment by slmjkdbtl** [comment]
@cn-80 Can you try again with `kaboom@next` and `import kaboom from "kaboom"`?

**Comment by WebdevAlexTV** [comment]
I can still not use the newest version. 

`import kaboom from "kaboom";

const k = kaboom({
  scale: 2,
  clearColor: [3, 211, 252, 1],
  width: 240,
  height: 384,
});

export default k;`

Installed version:
`"version": "2000.0.0-beta.13",`

Gives this error:
`index.js:19 Uncaught TypeError: _kaboom__WEBPACK_IMPORTED_MODULE_0__.default.start is not a function`

**Comment by slmjkdbtl** [comment]
@WebdevAlexTV Are you using webpack?

**Comment by slmjkdbtl** [comment]
Hmm I tested with create-react-app and webpack and they work on my local machine. Can you share config?

**Comment by slmjkdbtl** [comment]
Oh `start()` is removed in favor of `go()`, is that the problem?

**Comment by WebdevAlexTV** [comment]
Oh, it seems that start() was the Problem. So `import kaboom from "kaboom";` works fine :)

**Comment by slmjkdbtl** [comment]
Nice! I believe the package / bundler issue is resolve, closing.
