### ISSUE TITLE
Enable key combination support

### ISSUE THREAD

**Issue by oaklandgit** [replit/kaboom#76]
Hi,

Feature request:

I'd like to trigger an event when a key combination is pressed. It would be great to have some way to do this as part of the API, or at least a way to access the key state from within a loop:

```
k.action( ()=> {
        if( k.keyIsDown("shift") && k.keyIsDown("right") ) {
            …
        }
    }) 
```
Or maybe there's a way?

**Comment by slmjkdbtl** [comment]
They actually [exist](https://github.com/replit/kaboom/blob/84d0f5d098c9dcdcb0b9a235ea1ffe117564fa78/src/types.ts#L115-L118), but looks like missed in doc, will add soon.
