### ISSUE TITLE
Button playground example is using rbg() without arguments

### ISSUE THREAD

**Issue by magical-heyrovsky** [replit/kaboom#760]
https://github.com/replit/kaboom/blob/52763e7a2f1c57a96693e2c486133aab09d1a55d/examples/button.js#L42

But 3 arguments are required[^1]. Same here https://github.com/replit/kaboom/blob/52763e7a2f1c57a96693e2c486133aab09d1a55d/examples/collision.js#L115

[^1]: https://kaboomjs.com/#rgb

**Comment by slmjkdbtl** [comment]
`rgb()` is shorthand for `rgb(255, 255, 255)`, added it to the docs!
