### ISSUE TITLE
Prevent blue error screen

### ISSUE THREAD

**Issue by peratik** [replit/kaboom#773]
![image](https://github.com/replit/kaboom/assets/6568353/f5ce0155-c208-48c1-a95d-a25805a0caf7)

Hi, How can prevent blue error screen?

**Comment by slmjkdbtl** [comment]
Normally blue screen error means there's an error that's unrecoverable and should be fixed, but this one looks like a bug where someplace threw a string instead of an `Error`. Is there any console output?

**Comment by peratik** [comment]
the error is not related tokaboom codes.

**Comment by peratik** [comment]
Doesn't `onError` work for this?

**Comment by slmjkdbtl** [comment]
`onError` adds your own error handler but doesn't replace this error screen. If the error is unrelated to kaboom then it's a bug, it's fixed in `v3000.1.7`, you can try update kaboom to the latest version

**Comment by peratik** [comment]
Isn't `v3000.1.13` the latest version?

**Comment by slmjkdbtl** [comment]
You're already on v3000.1.13 and getting error screen from non-Kaboom Error? That's weird. What is the error, can you share the console output?

**Comment by peratik** [comment]
We use kaboom canvas inside an iframe. It may be a reason to that if there is already a fix. 
Error message in the parent iframe display inside kaboom that exists in child iframe.

**Comment by slmjkdbtl** [comment]
Do you have an example I can reproduce? Also what is the error message in the console output?

**Comment by peratik** [comment]
This is an example:

https://coffee-adria-35.tiiny.site/

Click on the button.

**Comment by slmjkdbtl** [comment]
Oh sorry I got it mixed up, the fix is not yet published, will be published to the next version soon

**Comment by peratik** [comment]
Hi, Any ETA for releasing the next version?

**Comment by slmjkdbtl** [comment]
v3000.0.15 is released, which includes the fix
