### ISSUE TITLE
Bug in flappy bird demo - No ceiling

### ISSUE THREAD

**Issue by coreysnodgrass** [replit/kaboom#80]
I was able to click the spacebar a bunch and fly over all the pipes and beat the game. It seems like there should be an upper level preventing you from doing that.

I used chrome v 91

**Comment by coreysnodgrass** [comment]
#85 - I created a PR for this.

**Comment by slmjkdbtl** [comment]
Hey! Thanks for the PR, but actually I'd prefer to have it just die if it's too high up: 8c9ee81 (also the `0.001` height rect might not trigger collision because the birdy might move through it between frames)
