### ISSUE TITLE
Support for .mp3 files in documentation

### ISSUE THREAD

**Issue by Aayam555** [replit/kaboom#81]

**Comment by Aayam555** [comment]
I can't find the way to load .mp3 files in kaboom.js website docs

**Comment by slmjkdbtl** [comment]
`.mp3` files should be loadable with `loadSound("attack", "sounds/attack.mp3")`

**Comment by Aayam555** [comment]
@slmjkdbtl yes but it is not shown in documentation. I wrote comment for this in examples for audio example. So please accept the pull request. And after that I will also write comments for other example files as well. Thank you

**Comment by slmjkdbtl** [comment]
Now most demos have proper documentations, closing this one
