### ISSUE TITLE
loadShader and loadSprite not defined in documentation

### ISSUE THREAD

**Issue by Aayam555** [replit/kaboom#83]
loadShader and loadSprite is not defined in documentation
Docs link: https://kaboomjs.com/

But it is used in examples
For example in this example: https://github.com/replit/kaboom/blob/45962a57a782e251fd6e0fe57b11f07d9c7d7c3c/examples/audio.js

**Comment by slmjkdbtl** [comment]
`loadSprite` should be on there, no?

`loadShader` is still experimental not officially released yet, thus not on doc now.

**Comment by Aayam555** [comment]
> `loadSprite` should be on there, no?
> 
> `loadShader` is still experimental not officially released yet, thus not on doc now.
