### ISSUE TITLE
Guide fails around #10

### ISSUE THREAD

**Issue by bestscarper** [replit/kaboom#88]
This was working earlier, but I backtracked, and it started failing.
MacOS Big Sur / fails identically with Chrome & Safari

https://kaboomjs.com/guide#10

<img width="683" alt="Screenshot 2021-06-28 at 23 38 06" src="https://user-images.githubusercontent.com/1479822/123712320-0069d180-d86a-11eb-89a2-7c1088611026.png">

**Comment by slmjkdbtl** [comment]
Thanks for catching this! Fixed in 9e63d64
