### ISSUE TITLE
import scenes from a different file

### ISSUE THREAD

**Issue by ghlai9665** [replit/kaboom#9]
Could you show an example of how to write a scene in a different file and then import it in? 

Right now I'm using absolute path to import i.e. `import { differentScene } from "/pub/examples/different_scene.js";`

This is working but is this best practice? Is there a way to support relative path importing?

**Comment by slmjkdbtl** [comment]
that sounds like a pretty good practice to me

> is there a way to support relative path importing

That's not related to kaboom and depends on your project setup. If you're using the example editor it's looking for files via HTTP requests, if you're developing locally and using a bundler or something, you should be able to do relative path importing

**Comment by srobertson421** [comment]
@ghlai9665 If you're familiar with ES modules, I have been building out a small test game using kaboom and I attempted a multi-file / module approach. I am using relative paths as that is what the browser requires. So far I think it's been working well for me but could still probably use some refactoring. Feel free to check it out here https://github.com/srobertson421/kaboom-space-shooter

@slmjkdbtl PS. Loving kaboom! The api is very clean and I am having a blast working with it. Thanks!

**Comment by slmjkdbtl** [comment]
@srobertson421 Thanks! and thanks for trying it out :D 

@ghlai9665 Hi! Is your issue resolved?
