### ISSUE TITLE
Scale to match size of display area.

### ISSUE THREAD

**Issue by storyfeet** [replit/kaboom#93]
Hi,

So when my game goes fullscreen, the game content doesn't scale to match.  I've tried various things to get around this.
eg making the kaboom on a canvas object and calling ```camScale(canvas.width/640)```, 

but can't seem to find a way to make it work.  Is there a way to do this, I'm missing?

**Comment by slmjkdbtl** [comment]
There can potentially be an option for different scale modes in `kaboom({...})`:
1. don't scale content (current behavior)
2. scale with aspect ratio (letterbox?)
3. scale stretched

**Comment by triptych** [comment]
This would be helpful for mobile viewports as well

**Comment by slmjkdbtl** [comment]
Now you can use 
```js
kaboom({
    // define game content size
    width: 640,
    height: 480,
    // if the canvas should stretch to parent size (default document.body)
    stretch: true,
    // if the canvas should keep aspect ratio when stretching, and leave black bars at empty space
    letterbox: true,
});
```

(`letterbox` is still kinda bugged atm)
