### ISSUE TITLE
[Donate] Github sponsors

### ISSUE THREAD

**Issue by ptkdev** [replit/kaboom#94]
Hi!
Please add github sponsors or patreon, i want donate and support this project.

**Comment by slmjkdbtl** [comment]
Hey! Thanks!

Right now we don't officially take github sponsors or patreon, another option is to go for a [hacker subscription on replit](https://replit.com/site/pricing) (it's on summer discount atm) which can support kaboom's development

**Comment by lirantal** [comment]
Same!
