### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by BARKHAC** [replit/kaboom#95]
hello , I am starting out with kaboom on repl.it and tried to initialize canvas by using a simple piece of code. It results in 'Script error' on console. Can someone please help me with the same?
kaboom.import();
init({
  width: 480,
  height: 360,
  scale: 2
});
 in my script.js file.

I have also imported kaboom by using the following tags in my html.
  <script src="https://kaboomjs.com/lib/master/kaboom.js"></script>
    <script src="https://kaboomjs.com/lib/master/kit/physics.js"></script>
    <script src="https://kaboomjs.com/lib/master/kit/starter.js"></script>
    <script src="https://kaboomjs.com/lib/master/kit/level.js"></script>

**Comment by triptych** [comment]
@BARKHAC this is not a support forum for Kaboom, but specifically for issues with the code. I would recommend you visit the Repl.it forums https://replit.com/talk/all?q=kaboom

**Comment by slmjkdbtl** [comment]
The old version used here is not supported anymore, please try to use the latest version and see if problem persists.
