### ISSUE TITLE
Tiling background example doesn't work

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#96]
Something's not working - at least on the website:  https://kaboomjs.com/examples#tiled

<img width="885" alt="vivaldi_orKNWXMEsI" src="https://user-images.githubusercontent.com/8691/125017308-b631de80-e027-11eb-9479-3897d4ab626c.png">

**Comment by slmjkdbtl** [comment]
weird, it rolled back itself to the previous version for some reason and had to recompile on the server (should work now), maybe some problem with the hosting

**Comment by slmjkdbtl** [comment]
It just went back itself again..

**Comment by triptych** [comment]
Yes, works for me now. Feel free to close.
