### ISSUE TITLE
Release is 0.5.1 but not "released" on github

### ISSUE THREAD

**Issue by triptych** [replit/kaboom#97]
Package.json says 0.5.1 --> https://github.com/replit/kaboom/blob/master/package.json#L4
But github site shows 0.5.0 as latest: 
<img width="267" alt="Screen Shot 2021-07-09 at 2 17 10 PM" src="https://user-images.githubusercontent.com/8691/125136815-60f5db80-e0c0-11eb-8c6e-caafea89736e.png">

**Comment by slmjkdbtl** [comment]
Didn't release v0.5.1 here because it only contains a `package.json` change, just tried and it can only release recent commits where I can't reach that one.. Sorry.
